CesiumForUnreal.uplugin
Source/CesiumEditor/CesiumEditor.Build.cs
Source/CesiumEditor/Private/CesiumIonSession.cpp
Source/CesiumEditor/Private/PCH.h
Source/CesiumRuntime/CesiumRuntime.Build.cs
Source/CesiumRuntime/Private/CesiumGltfComponent.cpp
Source/CesiumRuntime/Private/CesiumGltfComponent.h
Source/CesiumRuntime/Private/PCH.h
Source/CesiumRuntime/Private/UnrealAssetAccessor.cpp

Fix some minor build config and compilation errors.

Add support for Macos

---

Source/CesiumRuntime/Private/CesiumGltfComponent.cpp

Details discussed in https://github.com/CesiumGS/cesium-unreal/issues/315

Add gltfUpAxis support

---

CHANGES.md

As discussed during the call today: Added the changes since the 1.0.0 release

Update CHANGES.md with changes since 1.0.0

---

Source/CesiumRuntime/Private/Cesium3DTileset.cpp
Source/CesiumRuntime/Private/Cesium3DTilesetRoot.cpp
Source/CesiumRuntime/Private/CesiumGeoreference.cpp
Source/CesiumRuntime/Private/GlobeAwareDefaultPawn.cpp
Source/CesiumRuntime/Public/GlobeAwareDefaultPawn.h

Changes for fixing https://github.com/CesiumGS/cesium-unreal/issues/290 - details discussed in the issue.

Georeference validity checks

---

Source/CesiumRuntime/CesiumRuntime.Build.cs
Source/CesiumRuntime/Private/CesiumGltfComponent.cpp

This PR goes along with CesiumGS/cesium-native#208.

Update for glTF changes

---

CHANGES.md
CesiumForUnreal.uplugin
Documentation/release-process.md
Source/CesiumRuntime/CesiumRuntime.Build.cs
Source/CesiumRuntime/Private/UnrealAssetAccessor.cpp

Also added a really basic doc describing the release process. It needs to be updated with instructions for publishing to the Marketplace. Mind adding that @shehzan10?

Prepare v1.1.0 release

---

CHANGES.md
Source/CesiumRuntime/Private/Cesium3DTileset.cpp
Source/CesiumRuntime/Public/Cesium3DTileset.h
Source/CesiumRuntime/Public/CesiumExclusionZone.h

Further work to collision settings and exclusion zones

---

.travis.yml

Combine platform-specific plugin packages into one on CI

---

CHANGES.md
Source/CesiumRuntime/Public/Cesium3DTileset.h

Move the BodyInstance property to the Collision category so it works in the Editor

---

Documentation/release-process.md

Added one line to release process about testing foliage functionality.

Add foliage testing instructions

---

Documentation/reference-frames.md

Fix in reference frames documentation

---

Source/CesiumEditor/Private/CesiumEditor.cpp

Fixes https://github.com/CesiumGS/cesium-unreal/issues/485

Add support for small tool bar icons

---

Documentation/release-process.md

Rough steps for updating Cesium for Unreal Samples.
I've never done the marketplace side of the release, so if there are specific instructions for that, someone please add them.

Include Samples instructions in release process

---

Documentation/release-process.md

Let me know if I got any steps of this process wrong. Added a section for publishing Cesium Samples on Github and for publishing on the marketplace.

Add remainder of Samples release process

---

Source/CesiumRuntime/Private/Cesium3DTileset.cpp

Fix crash when undoing a tileset delete.

---

CHANGES.md
Source/CesiumEditor/Private/CesiumEditor.cpp
Source/CesiumEditor/Private/CesiumIonPanel.cpp
Source/CesiumRuntime/CesiumRuntime.Build.cs
Source/CesiumRuntime/Private/Cesium3DTileset.cpp
Source/CesiumRuntime/Private/CesiumBingMapsRasterOverlay.cpp
Source/CesiumRuntime/Private/CesiumCreditSystem.cpp
Source/CesiumRuntime/Private/CesiumGeoreference.cpp
Source/CesiumRuntime/Private/CesiumGeoreferenceComponent.cpp
Source/CesiumRuntime/Private/CesiumGltfComponent.cpp
Source/CesiumRuntime/Private/CesiumGltfComponent.h
Source/CesiumRuntime/Private/CesiumIonRasterOverlay.cpp
Source/CesiumRuntime/Private/CesiumRasterOverlay.cpp
Source/CesiumRuntime/Private/CesiumRuntime.cpp
Source/CesiumRuntime/Private/CesiumTileMapServiceRasterOverlay.cpp
Source/CesiumRuntime/Public/Cesium3DTileset.h
Source/CesiumRuntime/Public/CesiumBingMapsRasterOverlay.h
Source/CesiumRuntime/Public/CesiumCreditSystem.h
Source/CesiumRuntime/Public/CesiumGeoreferenceComponent.h
Source/CesiumRuntime/Public/CesiumGeoreferenceable.h
Source/CesiumRuntime/Public/CesiumIonRasterOverlay.h
Source/CesiumRuntime/Public/CesiumRasterOverlay.h
Source/CesiumRuntime/Public/CesiumTileMapServiceRasterOverlay.h
Source/CesiumRuntime/Public/GlobeAwareDefaultPawn.h

This PR accommodates https://github.com/CesiumGS/cesium-native/pull/301

Update name changing for Cesium3DTiles

---

.travis.yml

Same as CesiumGS/cesium-native#317 but now for cesium-unreal.

Fix Travis build failure.

---

CHANGES.md
Source/CesiumRuntime/Private/CesiumGeoreference.cpp

Choose nearest sublevel in the case of overlap

---

CHANGES.md
Source/CesiumRuntime/Private/GlobeAwareDefaultPawn.cpp

Fix fly-to crash when pawn isn't possessed

---

CHANGES.md
Source/CesiumRuntime/Private/Cesium3DTileset.cpp

Use correct FOV angle for Editor viewports

---

CHANGES.md
Source/CesiumRuntime/Private/Cesium3DTileset.cpp
Source/CesiumRuntime/Public/Cesium3DTileset.h
Source/CesiumRuntime/Public/CesiumBingMapsRasterOverlay.h
Source/CesiumRuntime/Public/CesiumIonRasterOverlay.h
Source/CesiumRuntime/Public/CesiumPolygonRasterOverlay.h
Source/CesiumRuntime/Public/CesiumRasterOverlay.h
Source/CesiumRuntime/Public/CesiumTileMapServiceRasterOverlay.h

Expose raster overlay properties to Blueprints.

---

.travis.yml
travis/travis-get-ue-427.sh

Add macOS / UE 4.27 build to Travis

---

Source/CesiumEditor/Private/CesiumIonSession.h
Source/CesiumRuntime/Private/CesiumGlobeAnchorComponent.cpp
Source/CesiumRuntime/Private/CesiumLifetime.cpp
Source/CesiumRuntime/Private/CesiumLifetime.h
Source/CesiumRuntime/Private/VecMath.cpp
Source/CesiumRuntime/Private/VecMath.h
Source/CesiumRuntime/Public/GeoTransforms.h
Source/CesiumRuntime/Public/UnrealAssetAccessor.h
Source/CesiumRuntime/Public/UnrealTaskProcessor.h

Fix build issues when bUseUnityBuild is false

---

CHANGES.md
Source/CesiumRuntime/Private/CesiumGltfComponent.cpp

Support the CESIUM_RTC glTF extension

---

CHANGES.md
Source/CesiumRuntime/Private/GlobeAwareDefaultPawn.cpp

Fix Gimbal Lock in "Innaccurate Fly to Location Longitude Latitude Height"

---

CHANGES.md
Source/CesiumRuntime/CesiumRuntime.Build.cs
Source/CesiumRuntime/Private/Cesium3DTileset.cpp
Source/CesiumRuntime/Public/Cesium3DTileset.h

Follow up to https://github.com/CesiumGS/cesium-native/pull/444, this PR exposes the cesium-native ion endpoint parameter in Cesium for Unreal.

Expose the ion endpoint as a parameter

---

ThirdParty.json

I'm still unsure about MikkTSpace license. They don't seem to have license file on their repo

Update third-party.json license

---

Source/CesiumRuntime/Private/CesiumWebMapServiceRasterOverlay.cpp
Source/CesiumRuntime/Public/CesiumWebMapServiceRasterOverlay.h

add CesiumWebMapServiceRasterOverlay component

---

Source/CesiumRuntime/Public/Cesium3DTilesetLoadFailureDetails.h
Source/CesiumRuntime/Public/CesiumFeatureTextureProperty.h
Source/CesiumRuntime/Public/CesiumRasterOverlayLoadFailureDetails.h
Source/CesiumRuntime/Public/CustomDepthParameters.h

Initialize fields of UStructs.

---

.github/workflows/build.yml
CHANGES.md

This is PR into #844 so merge that first.

Add iOS / UE5 build to CI

---

CHANGES.md
Source/CesiumRuntime/Private/CesiumLifetime.cpp

This is the PR to UE-4 main from https://github.com/CesiumGS/cesium-unreal/pull/873

Update UE4 to explicitly remove Physics Data

---

package.json

Bump package.json version, update cesium-native

Merge u4-main into ue5-main

---

Source/CesiumRuntime/Private/ScreenCreditsWidget.cpp

changed to branch from ue4-main

fix warnings when packaging ios project

---

Documentation/developer-setup-windows.md

- Updates the set up guide for Windows system to include .NET, which is a dependency for Unreal Engine.

Update Windows Setup Instructions for VS

---

CHANGES.md
Source/CesiumEditor/Private/CesiumIonSession.cpp
Source/CesiumEditor/Private/CesiumSourceControl.cpp
Source/CesiumEditor/Private/CesiumSourceControl.h
Source/CesiumEditor/Private/SelectCesiumIonToken.cpp
Source/CesiumEditor/Private/SelectCesiumIonToken.h

Fix Perforce issue when saving tokens

---

CHANGES.md
Source/CesiumRuntime/Private/CesiumGlobeAnchorComponent.cpp
Source/CesiumRuntime/Public/CesiumGlobeAnchorComponent.h

Fix Globe Anchor Component preventing Actor transform from resetting/changing.

---

CHANGES.md
Source/CesiumRuntime/Private/Cesium3DTileset.cpp

I also updated the changelog to mention https://github.com/CesiumGS/cesium-unreal/pull/963.

Update cesium-native, update unreal code for a small breaking change.

---

.github/workflows/build.yml

The updated build machine images build much faster, too!

Remove installation of unnecessary dependencies.

---

CHANGES.md
Source/CesiumRuntime/Private/Cesium3DTileset.cpp
Source/CesiumRuntime/Private/CesiumGltfComponent.cpp
Source/CesiumRuntime/Private/CreateGltfOptions.h
Source/CesiumRuntime/Private/LoadGltfResult.h
Source/CesiumRuntime/Public/Cesium3DTileset.h

Fix shiny Tileset when using KHR Materials Unlit

---

Source/CesiumRuntime/Private/UnrealAssetAccessor.cpp
Source/CesiumRuntime/Public/UnrealAssetAccessor.h

Cesium Request Headers

---

CHANGES.md

Updates Cesium Native to the May release

Update Cesium Native

---

CHANGES.md
Source/CesiumRuntime/Private/CesiumRuntime.cpp
Source/CesiumRuntime/Public/CesiumRuntimeSettings.h

Add settings to manipulate cache pruning

---

.github/workflows/build.yml
Source/CesiumRuntime/Private/GlobeAwareDefaultPawn.cpp
Source/CesiumRuntime/Public/GlobeAwareDefaultPawn.h

Apparently we only ever had this in UE4.

Add formatting check to CI

---

CHANGES.md
Source/CesiumRuntime/Private/CesiumCameraManager.cpp
Source/CesiumRuntime/Private/Tests/CesiumCameraManager.spec.cpp
Source/CesiumRuntime/Private/Tests/GeoTransforms.spec.cpp
Source/CesiumRuntime/Public/CesiumCameraManager.h

Add null pointer check in ACesiumCameraManager::GetDefaultCameraManager.
Add new unit tests for CesiumCameraManager.
Closes #1056

Add ACesiumCameraManager::RemoveCamera

---

Source/CesiumRuntime/Private/CesiumCameraManager.cpp
Source/CesiumRuntime/Private/CesiumSunSky.cpp
Source/CesiumRuntime/Private/Tests/CesiumCameraManager.spec.cpp
Source/CesiumRuntime/Public/CesiumCreditSystem.h

ue5-main broke on UE5.2 / Clang platforms with commit https://github.com/CesiumGS/cesium-unreal/commit/205edbbd4f00a46f62c64ea97f557aac36364003, but it's really not clear why. I can't see anything wrong with the commit itself. I was able to fix it by adding some missing includes. Perhaps the addition of a new (test) source file just made the Unreal Built Tool reorganize how it grouped various source files together for the unity build process, exposing the missing include.
Also some formatting changes here to make clang-format happy.

Fix broken UE 5.2 build on Clang platforms (Linux, Android, macOS, iOS)

---

CHANGES.md
Source/CesiumRuntime/Private/CesiumGeoreference.cpp
Source/CesiumRuntime/Private/CesiumSunSky.cpp
Source/CesiumRuntime/Public/CesiumGeoreference.h

Add method to get/set georeference scale by blueprint

---

Source/CesiumRuntime/Private/ScreenCreditsWidget.cpp

Exposed by recent AWS outage...

Check if credit texture load succeeds before proceeding

---

CHANGES.md
Source/CesiumEditor/Private/CesiumEditor.cpp
Source/CesiumRuntime/Private/Cesium3DTileset.cpp
Source/CesiumRuntime/Private/CesiumCameraManager.cpp
Source/CesiumRuntime/Private/CesiumCreditSystem.cpp
Source/CesiumRuntime/Private/CesiumGeoreference.cpp
Source/CesiumRuntime/Private/CesiumGlobeAnchorComponent.cpp
Source/CesiumRuntime/Private/CesiumSubLevelComponent.cpp
Source/CesiumRuntime/Private/CesiumSunSky.cpp
Source/CesiumRuntime/Public/Cesium3DTileset.h
Source/CesiumRuntime/Public/CesiumGlobeAnchorComponent.h
Source/CesiumRuntime/Public/CesiumSubLevelComponent.h

See the CHANGES.md update for a summary of what's new in this PR.
Fixes #273
Fixes #1069

More improvements to the sub-level system

---

Documentation/developer-setup-windows.md

Fix broken links in Windows developer setup docs

Update developer setup documentation

---

Config/Engine.ini

Fix the syntax of a couple of the core redirects.

---

Source/CesiumEditor/Private/Cesium3DTilesetCustomization.h
Source/CesiumEditor/Private/CesiumEditor.cpp
Source/CesiumRuntime/Private/CesiumPointAttenuationVertexFactory.h

I ran into these because I'm building without "unity" mode, but they're (small) legitimate problems.

Add missing headers and forward declarations

---

CHANGES.md
Source/CesiumRuntime/Private/CesiumTile.cpp

Fix Tile Excluder bug

---

CHANGES.md
Source/CesiumRuntime/Private/Tests/UnrealAssetAccessor.spec.cpp
Source/CesiumRuntime/Private/UnrealAssetAccessor.cpp

Check and remove query params from file URLs

---

CHANGES.md
Source/CesiumRuntime/Private/Cesium3DTileset.cpp
Source/CesiumRuntime/Public/Cesium3DTileset.h

Fix EditCondition error when checking if platform is Mac

---

CHANGES.md
Source/CesiumEditor/Private/SelectCesiumIonToken.cpp

Fix "Select New Token" dialog when not connected to ion

---

.github/workflows/build.yml
.github/workflows/buildWindows.yml
.github/workflows/testPackageOnWindows.yml
.github/workflows/testWindows.yml

The biggest improvement here is that it should allow us to access artifacts of intermediate build steps before the entire workflow is complete.

Upgrade to v4 of download/upload-artifact

---

Source/CesiumEditor/Private/CesiumIonTokenTroubleshooting.cpp
Source/CesiumRuntime/Private/CesiumSubLevelSwitcherComponent.cpp
Source/CesiumRuntime/Private/CesiumTextureUtility.cpp

Fixes #1314
Fixes several UE5.3 build warnings when packaging.

UE5 build warning fixes

---

.github/actions/install-unreal-linux/action.yml
.github/workflows/build.yml
.github/workflows/buildWindows.yml

This builds on #1385 because main is broken.
Closes #1400

Add CI for Unreal Engine 5.4

---

Source/CesiumEditor/Private/CesiumIonSession.cpp

As mentioned here:
https://github.com/CesiumGS/cesium-unreal/pull/1385#discussion_r1586023049

Fix copy/paste error that breaks Cesium ion sign-in

---

Config/FilterPlugin.ini

Add Editor.ini to FilterPlugin.ini

---

CHANGES.md
Source/CesiumRuntime/Private/CesiumGltfComponent.cpp

fix https://github.com/CesiumGS/cesium-unreal/issues/1160

remove the baseColorFactor alpha check when selecting base material

---

CHANGES.md
Source/CesiumRuntime/Private/CesiumGltfComponent.cpp

Manually copy vertices to work around UE 5.3/5.4 bug.

---

Source/CesiumRuntime/Private/Cesium3DTileset.cpp
Source/CesiumRuntime/Private/CesiumEncodedFeaturesMetadata.cpp
Source/CesiumRuntime/Private/CesiumEncodedFeaturesMetadata.h
Source/CesiumRuntime/Private/CesiumEncodedMetadataUtility.cpp
Source/CesiumRuntime/Private/CesiumEncodedMetadataUtility.h
Source/CesiumRuntime/Private/CesiumGltfTextures.cpp
Source/CesiumRuntime/Private/CesiumPropertyTextureProperty.cpp
Source/CesiumRuntime/Private/CesiumTextureResource.cpp
Source/CesiumRuntime/Private/CesiumTextureResource.h
Source/CesiumRuntime/Private/CesiumTextureUtility.cpp
Source/CesiumRuntime/Private/CesiumTextureUtility.h
Source/CesiumRuntime/Private/ExtensionImageAssetUnreal.cpp
Source/CesiumRuntime/Private/ExtensionImageAssetUnreal.h
Source/CesiumRuntime/Private/Tests/Cesium3DTileset.spec.cpp
Source/CesiumRuntime/Private/Tests/CesiumPropertyTextureProperty.spec.cpp
Source/CesiumRuntime/Private/Tests/CesiumTextureUtility.spec.cpp
Source/CesiumRuntime/Public/CesiumPropertyTextureProperty.h

https://github.com/CesiumGS/cesium-native/pull/965
This is a PR into #1527.

Update cesium-unreal to work with shared-assets-tweaks branch of cesium-native

---

Source/CesiumRuntime/Private/Cesium3DTileset.cpp
Source/CesiumRuntime/Private/CesiumTextureResource.cpp
Source/CesiumRuntime/Private/Tests/Cesium3DTileset.spec.cpp

The Unreal side of https://github.com/CesiumGS/cesium-native/pull/971.
This is a PR into #1521.

Update cesium-unreal for shared asset changes

---

Source/CesiumRuntime/Private/CesiumEncodedFeaturesMetadata.h
Source/CesiumRuntime/Private/CesiumGltfComponent.cpp
Source/CesiumRuntime/Public/CesiumCommon.h

Fix UE 5.5 crash with hardware ray tracing enabled

---

Source/CesiumRuntime/Private/Tests/CesiumPropertyTable.spec.cpp
Source/CesiumRuntime/Private/Tests/CesiumPropertyTexture.spec.cpp

Fixes the build after CesiumGS/cesium-native#969.
~Requires CesiumGS/cesium-native#999.~
Requires CesiumGS/cesium-native#1002

Update for schema changes in cesium-native

---

CHANGES.md
Source/CesiumRuntime/Private/Cesium3DTileset.cpp
Source/CesiumRuntime/Public/Cesium3DTileset.h

Hi,
Pretty much the same as https://github.com/CesiumGS/cesium-unity/pull/467, but for Unreal :)

Add support for ellipsoid tileset loader

---

.github/workflows/prod.yml
Documentation/Doxyfile

Fixes #1377 
This doesn't work yet due to S3 permissions.

Publish documentation to the web site

---

Source/CesiumRuntime/Private/CesiumSubLevelSwitcherComponent.cpp

I forgot an enum check in my previous PR #1576 
The bug still occurs unless if this is also done!

Treat failed to load as unloaded sublevels Pt. 2

---

CHANGES.md
CesiumForUnreal.uplugin
package.json

Merging the v2.13.2 patch release back into main.

Incorporate v2.13.2 patch release

---

Source/CesiumRuntime/Private/CesiumGlobeAnchoredActorComponent.cpp
Source/CesiumRuntime/Private/CesiumMetadataUtilityBlueprintLibrary.cpp
Source/CesiumRuntime/Private/CesiumTile.cpp
Source/CesiumRuntime/Private/VecMath.h
Source/CesiumRuntime/Public/CesiumTile.h
Source/CesiumRuntime/Public/CesiumTileExcluder.h

This was breaking, probably due to some quirk of the unity build

Add includes for compilation on Linux

---

.github/workflows/prod.yml

I made this change in the `cesium.com` branch in order to fix some weirdness in the official generated docs. This PR is just to bring it back into main.

Upgrade to doxygen 1.13.2.

---

CHANGES.md
Source/CesiumRuntime/Private/Tests/GoogleTilesTestSetup.cpp

https://community.cesium.com/t/compilation-error-with-v2-15-0/39721

Fix linker issue in GoogleTilesTestSetup.cpp

---

Source/CesiumRuntime/Private/Cesium3DTileset.cpp
Source/CesiumRuntime/Public/Cesium3DTileset.h

This is a PR into #1648 to update cesium-unreal for CesiumGS/cesium-native#1156.

Multiple views: use one reference count branch

---

CHANGES.md
Source/CesiumRuntime/Private/CesiumCreditSystem.cpp

Fix for release v2.16.0
Mentioned in #1666

Add missing include in CesiumCreditSystem.cpp (fix #1666)

---

Documentation/performance-profiling-with-unreal-insights.md

Hopefully straightforward. :smile:

Fix broken link in performance documentation

---

Source/CesiumRuntime/Private/Cesium3DTileset.cpp
Source/CesiumRuntime/Private/Tests/CesiumSceneGeneration.cpp
Source/CesiumRuntime/Private/Tests/TileLoadingSoakTest.cpp
Source/CesiumRuntime/Public/Cesium3DTileset.h

This PR updates cesium-unreal to work with the breaking changes to cesium-native in this PR:
https://github.com/CesiumGS/cesium-native/pull/1221

Use `const-get-root-tile` branch of cesium-native
