CesiumGS/cesium-unreal

- Source/CesiumRuntime/Private/Cesium3DTileset.cpp
Combined with CesiumGS/cesium-native#193, this greatly reduces the amount of information written to the Output window by default, making it more likely that we (and users) notice real problems.
> Log selection stats at Verbose instead of Display level.

- Source/CesiumRuntime/Private/CesiumGltfComponent.cpp
- Source/CesiumRuntime/Private/CesiumGltfComponent.h
- Source/CesiumRuntime/Public/Cesium3DTileset.h
Closing #317 
@argallegos I quickly checked this by creating a material instance of `GltfMaterialWithOverlays` and setting that as the Material in CesiumWorldTerrain, and the terrain rendered normally (same as if there was no reference set there). Are there other tests to make sure this is working correctly?
> Change UMaterial references to UMaterialInterface

- Source/CesiumRuntime/Private/Cesium3DTileset.cpp
- Source/CesiumRuntime/Public/Cesium3DTileset.h
- Source/CesiumRuntime/Public/CesiumExclusionZone.h
Added Bodyinstance Property to define tiles collision settings on a per-actor basis
Added ExclusionZones concept to cull OSM Buildings when displaying photogrammetry assets
Added BueprintReadOnly flag to CesiumIonToken to be able to check that tokens have been set...
> Added Collision Settings and Exclusion Zones

- CHANGES.md
- Source/CesiumRuntime/Private/CesiumGeoreference.cpp
This can cause round-trip errors on the order of tens of centimeters, when it should be many orders of magnitude less than that. Reported here:
https://community.cesium.com/t/solved-about-transform-location/13255/7
> Fix truncation of ECEF values to float.

- travis/travis-get-ue.sh
macOS builds don't run on Google Cloud like Windows and Linux builds do, so downloading it from GCS isn't free. And GCS costs more than S3, so let's use S3.
> Get UE for macOS from AWS S3 instead of Google GCS.

- CHANGES.md
- Source/CesiumRuntime/Private/Cesium3DTileset.cpp
- Source/CesiumRuntime/Private/CesiumGltfComponent.cpp
- Source/CesiumRuntime/Public/Cesium3DTileset.h
Small clean up of the checks for property changes in `Cesium3DTileset::LoadTileset`.
> Property change checks improved for watermask

- Source/CesiumRuntime/Private/Cesium3DTileset.cpp
- Source/CesiumRuntime/Private/CesiumGltfComponent.cpp
Fixes #313 
Also fixes a bug where all the tiles would disappear if you turned on "Suspend Update". And gives our UStaticMeshes a name (the tile URL) so they're easier to identify.
Here come a lot of words about the cause and solution of this issue...
When creating the UStaticMeshComponent instances, we set `bUseDefaultCollision=true` on it. Why? Well, probably because I saw the DataSmith glTF loader code doing something similar and didn't know any better.
Anyway, it turns out that what that property actually means is that the collision profiles should come from the `BodySetup` of the  `UStaticMesh` attached to the component, rather than from the CesiumGltfPrimitiveComponent's `BodyInstance`. That's a problem because we're turning collision on and off (e.g. when the tile isn't visible) …
> Always use the glTF primitive component's collision, not the static mesh's.

- CHANGES.md
- Source/CesiumRuntime/Private/CesiumGeoreferenceComponent.cpp
When using 'MoveToLongitudeLatitudeHeight' function, only ECEF properties are updated.
When using 'InaccurateMoveToLongitudeLatitudeHeight', only "geographics" (lat/long/height) properties are updated.
Fixing this by updating both types of properties regardless of the called function.
> Fixing GeoreferenceComponent properties update 

- CHANGES.md
- Source/CesiumRuntime/Private/CesiumGeoreference.cpp
The georeference matrices were being initialized to zero after #319. This PR initializes them to identity again, possibly fixing: #407.
> Initialize georeference matrices with identity, not zero

- CHANGES.md
- Source/CesiumRuntime/Private/CesiumGeoreference.cpp
This is the core of what was originally done in https://github.com/CesiumGS/cesium-unreal/pull/409 : 
It only makes sure that the rebased world origin stays in the integer range.
(EDIT: Fixes https://github.com/CesiumGS/cesium-unreal/issues/284 )
> Fix zooming limit only

- Source/CesiumEditor/Private/CesiumPanel.h
- Source/CesiumEditor/Private/IonLoginPanel.h
- Source/CesiumEditor/Private/IonQuickAddPanel.h
- Source/CesiumRuntime/Private/CesiumCreditSystem.cpp
- Source/CesiumRuntime/Private/SpdlogUnrealLoggerSink.cpp
- Source/CesiumRuntime/Private/UnrealAssetAccessor.cpp
- Source/CesiumRuntime/Public/CesiumGlobeAnchorParent.h
Whenever I edit some files locally, Unreal will exclude them from the unity blob and the build will start failing because of these missing includes.
> Add a couple missing #include to be able to compile with -DisableUnity.

- CHANGES.md
- Source/CesiumRuntime/Private/CesiumGeoreferenceComponent.cpp
- Source/CesiumRuntime/Public/CesiumGeoreferenceComponent.h
Closes #307 
I added a bool UPROPERTY which determines whether the teleport setting is set to None or TeleportPhysics. Perhaps it'd be a good idea to expose all three options here instead of a boolean?
UE documentation regarding this flag:
```
/** Whether to teleport physics body or not */
UENUM()
enum class ETeleportType : uint8
{
/** Do not teleport physics body. This means velocity will reflect the movement between initial and final position, and collisions along the way will occur */
None,
/** Teleport physics body so that velocity remains the same and no collision occurs */
TeleportPhysics,
/** Teleport physics body and reset physics state completely */
ResetPhysics,
};
```
Also found this page from the UE blog helpful: https://www.unrealengine.com/en-US/blog/moving-physical-objects
> Added teleport flag for cesium georeference transform update

- Source/CesiumRuntime/Private/CesiumRuntime.cpp
First load needs to happen inside GameThread.
Since we always use it through async, we could crash if nobody ended up loading the HTTP module before we did.
Addressing issue reported in https://github.com/CesiumGS/cesium-unreal/issues/439
> Ensure HTTP module gets loaded along with Runtime.

- Source/CesiumRuntime/Private/Cesium3DTileset.cpp
- Source/CesiumRuntime/Private/CesiumGltfComponent.cpp
- Source/CesiumRuntime/Public/Cesium3DTileset.h
I don't have a Mac to test this on, but this should prevent a horrible crash on Mac that seems to be caused by using the water material. In the future once we figure out what's causing it, we may be able to come up with a fix that allows water mask to be supported on Mac.
> Disable support for water mask on Mac

- Source/CesiumRuntime/Private/Cesium3DTileset.cpp
Fixes https://github.com/CesiumGS/cesium-unreal/issues/491
The original comment there said
TODO: Not-yet-renderable tiles shouldn't be here.
*If* these tiles should not be in the "tiles to render" vector in the first place, then this TODO could be converted into an issue. 
Further actions then depend on whether it is sensibly possible to avoid this case, or to detect the case that a tile **will** have a glTF and (unexpectedly) does **not** have it (despite the LoadState being checked first). Maybe some check based on the tile content or so...?
However, for now, the warning is turned into a comment, saying under which conditions the "tiles to render" do not really have something to render.
> Omit warning about missing glTFs

- CHANGES.md
- Source/CesiumRuntime/Private/CesiumGltfComponent.cpp
We receive the asset that has `UNSIGNED_BYTE` for the index accessor, but the plugin only supports `UNSIGNED_SHORT` and `UNSIGNED_INT`. This PR adds support for the rest too.
@kring I just quickly add a tile content inspector actor in this branch https://github.com/CesiumGS/cesium-unreal/tree/TileContentInspector. It should render the tile content by passing the URL to it for a check
> Implement other types of index accessor

- Documentation/developer-setup-windows.md
- Documentation/packaging-guide.md
- Linked to Unreal's Android installation guide which is a detailed walkthrough of setting up Android Studio and NDK.  https://docs.unrealengine.com/SharingAndReleasing/Mobile/Android/Setup/AndroidStudio/
- Added step to install Ninja
- Added reminders at certain points in the build/packaging process for Android so that users don't skip them and run into errors, as the steps are scattered across different sections of different docs.
> Android build docs update

- CHANGES.md
- Source/CesiumRuntime/Private/Cesium3DTileset.cpp
- Source/CesiumRuntime/Public/Cesium3DTileset.h
Fixes CesiumGS/cesium-native#186.
The one-frame holes happen when we switch between LODs and the timing is just right so that Unreal Engine ends up using previously cached (and incorrect) occlusion information for the new LOD. A new occlusion query sorts it out quickly for the next frame, but not before the user can notice a flash of part of the model missing.
There doesn't appear to be a way to clear the stale occlusion information, so instead I've implemented a bit of a hack. On each Tick, we get a new list of tiles to hide this frame. But we don't actually hide them. Instead, we copy the list to a separate list, and we hide the tiles in that list _next_ frame. So effectively there's a one-frame delay for all tile hiding. That will mean briefly showing two LODs together for one frame, …
> Fix one-frame holes in models.

- Documentation/developer-setup.md
Feel free to suggest a different place to put this documentation, but I just added in a note on how developers can run clang on their code before checking it in. I didn't know the exact commands until last week, so I'm sure this will be helpful for future contributors. 
As something else to think about, Matt A suggested running `npm run format` on commit, as is done in the Cesium JS repos.
> Added formatting documentation

- Source/CesiumRuntime/Private/CesiumGltfComponent.cpp
- Source/CesiumRuntime/Public/Cesium3DTileset.h
Fixes #524 
Note that the skip-the-tangents optimization in #499 are still a significant win even though we're rolling them back a bit here. We still don't need to generate tangents for: photogrammetry models (which have much more complicated geometry than terrain), and terrain tiles without any water.
> Generate tangents for water tiles

- Source/CesiumEditor/Private/CesiumPanel.cpp
- Source/CesiumEditor/Private/IonQuickAddPanel.cpp
fixes #532 
The SunSky was not initializing to the correct georeference when spawned through the quick add panel. I'm sure the SunSky handling will be improved drastically once the georeference and sunsky refactoring are done, but here is a fix for now.
@argallegos Can you review?
> Small fixes to the quick-add panel 

- Source/CesiumRuntime/Private/Cesium3DTileset.cpp
Fixes #487 
~(maybe)~ (the original reporter has confirmed it fixes the issue)
> Get camera parameters using GetCameraViewPoint and GetFOVAngle instead of ViewTarget

- .travis.yml
- Source/CesiumEditor/CesiumEditor.Build.cs
- Source/CesiumRuntime/CesiumRuntime.Build.cs
- travis/travis-get-ue.sh
If you all loved my hacky approach to compiling cesium-native with C++14, wait til ya get a load of this! :laughing: 
So the problem is that, prior to UE 4.26.2, the Unreal Build Tool ignores the CppStandard option on the plugin and instead just always passes `-std=c++14` to clang. Well, after tracing through the `AndroidToolChain.cs` file in the UE source where the Android build process is implemented, I realized that there's an `AdditionalArguments` property passed into there on a `CompileEnvironment` object. And I also learned that clang, conveniently, doesn't care if you pass multiple -std=c++X arguments and it just uses the last one. So if I could just figure out how to set that `AdditionalArguments` property, we could force clang to compile in C++17 mode even though UE is trying to …
> Sneakily force C++17 mode in Android builds

- Source/CesiumRuntime/Private/Cesium3DTileset.cpp
- Source/CesiumRuntime/Private/Cesium3DTilesetRoot.cpp
- Source/CesiumRuntime/Private/CesiumActors.cpp
- Source/CesiumRuntime/Private/CesiumActors.h
- Source/CesiumRuntime/Private/CesiumGeoreference.cpp
- Source/CesiumRuntime/Private/CesiumGeoreferenceComponent.cpp
- Source/CesiumRuntime/Private/CesiumGlobeAnchorParent.cpp
- Source/CesiumRuntime/Private/CesiumSunSky.cpp
- Source/CesiumRuntime/Private/CesiumSunSky.h
- Source/CesiumRuntime/Private/GlmLogging.cpp
- Source/CesiumRuntime/Private/GlmLogging.h
- Source/CesiumRuntime/Private/GlobeAwareDefaultPawn.cpp
- Source/CesiumRuntime/Private/VecMath.cpp
- Source/CesiumRuntime/Public/CesiumGeoreference.h
- Source/CesiumRuntime/Public/CesiumGeoreferenceComponent.h
- Source/CesiumRuntime/Public/GeoTransforms.h
Potentially fixes #422, #494, #498
Copying @javagl's notes:
- The `CesiumGeoreferenceComponent` now an ActorComponent, and no longer a SceneComponent. So it does not have a "transform" on its own. (This transform had to be ignored in the old state).
- It's now using the Ellipsoid of the GeoRef instead of the fixed WGS84
- The representation of the "position" is now solely encoded in the ECEF_X/Y/Z properties. Originally, it had at least 3 (but I think maybe even 5 or 6) representations of "the position", and keeping them consistent was hard.
The goal is to merge into `bp-function-library` after verifying a) correct behavior of georeferenced objects, and b) backwards compatibility with georeferenced actors created with the old version of this component.
@nithinp7 mentioned some issues with …
> Georeference component refactoring / fixes

- Source/CesiumRuntime/Private/Cesium3DTileset.cpp
- Source/CesiumRuntime/Private/CesiumGltfComponent.cpp
- Source/CesiumRuntime/Public/Cesium3DTileset.h
Fixes #573
* Remove the `_tilesetIsDirty` is flag. Instead, just destroy the Cesium3DTiles::Tileset when necessary.
* Create all of our components and materials with flags `RF_Transient | RF_DuplicateTransient | RF_TextExportTransient`. This prevents all the transient glTF components a tileset creates on the fly from being included when doing a cut/copy/paste, which in turn prevents warnings when pasting a tileset.
* Implemented `PostEditUndo` and `PostEditImport` to recreate the tileset after undo/redo and paste, respectively.
Things I tested (and found to work):
* Delete a tileset, then undo (it comes back).
* Edit a tileset's asset ID, then undo the change (the original asset ID is loaded successfully).
* Edit a tileset's SSE, and then undo the change (the tileset is recreated with the …
> Improvements to tileset life cycle, undo/redo, and copy/paste

- CHANGES.md
- Source/CesiumRuntime/Private/CesiumMetadataFeatureTable.cpp
> Round feature IDs to the nearest integer so they work in Draco-compressed meshes

- CHANGES.md
- Source/CesiumRuntime/Private/Cesium3DTileset.cpp
- Source/CesiumRuntime/Public/Cesium3DTileset.h
Adds tile-selection compatibility for using `ASceneCapture2D` actors. The scene capture actor can now be used for things such as mini-maps, security cameras, mirrors, etc. alongside Cesium tilesets. 
https://user-images.githubusercontent.com/6706316/129304569-562382ec-63af-4dc7-aa1a-36c0326fc5d7.mp4
> Find scene capture frustums for tile selection

- CHANGES.md
- Source/CesiumEditor/Private/CesiumEditor.cpp
Fixes #613 
It is still awkward to add new overlays with the drape button since new overlays require a different material layer key to be entered. Since the default material layer key is "Overlay0", the new overlay may appear to replace parts of the existing overlay. This PR only makes sure that the old overlays aren't outright deleted from the tileset's components list.
> Fixed "Drape Over Terrain Tileset" deleting existing overlays.

- CHANGES.md
- Source/CesiumEditor/Private/CesiumEditor.cpp
- Source/CesiumEditor/Private/CesiumEditor.h
- Source/CesiumEditor/Private/CesiumIonPanel.cpp
- Source/CesiumEditor/Private/CesiumIonPanel.h
- Source/CesiumEditor/Private/IonQuickAddPanel.cpp
Following on from #614...
When using the Quick-Add panel, users almost certainly want to _replace_ the base raster overlay rather than adding another on top. When using the Cesium ion Assets panel, either possibility is pretty likely. So in this PR, I've made the Quick Add panel replace `Overlay0` with the new asset. And I've added a second button to the Cesium ion Assets panel allowing the user to choose:
The first button replaces `Overlay0`, just like the Quick-Add does.
The second button assigns the first unused `OverlayN` MaterialLayerKey to the new component.
This still isn't perfect UX-wise, but it's a big improvement I think.
> Improved UX for adding raster overlays with the Cesium panels

- .travis.yml
Unlike our 4.26 builds, this one is not ready to use. But it should be sufficient for submitting to the Marketplace.
> Make Travis build a simple package for UE 4.27.

- Config/FilterPlugin.ini
Without this change, the Engine.ini with our CoreRedirects doesn't get included in the plugin package. Which means a broken level blueprint in the Metadata sample and elsewhere.
> Include Engine.ini in plugin package.

- .travis.yml
The 4.26 plugin binaries won't be usable in 4.27, but the cesium-native libs will be and as long as those are available the Editor will be able to recompile the plugin binaries for 4.27 on load (as long as the user has the necessary C++ toolchain installed). This is a temporary workaround until we can get our macOS toolchain sorted for 4.27.
> Include 4.26 macOS builds in the 4.27 package.

- CHANGES.md
- Source/CesiumRuntime/Private/Cesium3DTileset.cpp
- Source/CesiumRuntime/Public/Cesium3DTileset.h
Greetings of the day @kring,
Please review the PR and let me know in case of any changes if required.
Fixes : #633
> Added maximumCachedBytes as a UPROPERTY

- Documentation/developer-setup-windows.md
- Documentation/packaging-guide.md
Saw I had originally included a broken link in the docs that was pointing to an old branch instead of main. Fixed it.
> Updated broken link in build docs

- .travis.yml
The Travis macOS image doesn't automatically update homebrew, and its p7zip record has a URL that has recently become invalid. This makes all our macOS builds fail to install 7zip, which in turn makes them fail to publish the built package. This PR fixes that by telling homebrew to update.
> Add homebrew update to fix macos build.

- .travis.yml
- CHANGES.md
- Source/CesiumRuntime/Private/CesiumGltfComponent.cpp
Fixes #652 
In addition to fix the tangent computation order, I noticed and fixed a bug where an unitialized `LoadModelResult::waterMaskTexture` pointer, if it happened to not be null, would make us erroneously think we needed to duplicate vertices and generate tangents.
> Compute tangents after UVs are set, and initialize LoadModelResult fields

- CHANGES.md
- Source/CesiumEditor/Private/CesiumIonPanel.cpp
- Source/CesiumEditor/Private/CesiumIonPanel.h
- Source/CesiumEditor/Private/CesiumIonSession.cpp
- Source/CesiumEditor/Private/CesiumIonSession.h
Fixes #647 
Here's how to reproduce it:
1. Launch the Unreal Editor.
2. Either close the Cesium panel or make it hidden (i.e. by selecting another tab in its tab group, like Place Actors).
3. Open the Cesium ion Assets panel and make it active.
4. Close the Editor, then start it up again. The editor should remember your last state, so the Cesium ion Assets panel should be visible but the Cesium panel should not be. The Cesium ion Assets panel should have a list of assets in it.
5. Select any asset from the list and add it.
The new tileset will be created with a blank access token. If you remove and re-add it, it will have the right token the second time.
The problem was that the Assets panel wasn't ensuring we had a valid token (and loading it if necessary) before allowing assets to be …
> Don't show ion assets until we have a token.

- Source/CesiumRuntime/Public/Cesium3DTileset.h
- Source/CesiumRuntime/Public/CesiumGlobeAnchorComponent.h
- Source/CesiumRuntime/Public/CesiumSubLevel.h
Without these, installing the plugin as an engine plugin and attempting to package fails with a bunch of errors, as seen in #673.
> Add missing category specifiers

- .travis.yml
- Source/CesiumRuntime/CesiumRuntime.Build.cs
- Source/CesiumRuntime/Private/Cesium3DTileset.cpp
- Source/CesiumRuntime/Private/CesiumGeoreference.cpp
- Source/CesiumRuntime/Private/CesiumGlobeAnchorComponent.cpp
- Source/CesiumRuntime/Private/GeoTransforms.cpp
- Source/CesiumRuntime/Private/VecMath.cpp
- Source/CesiumRuntime/Private/VecMath.h
Cherry picked from #679. My comment from there:
> This PR also switches our Travis macOS build to use xcode 12 instead of 11.3, because 11.3 uses macOS 10.14 and is apparently not supported by homebrew anymore, so it does a bunch of compilation from source and times out. 🙄 Using xcode 12 might be ok (it's the "recommended" xcode version for UE 4.26), or it might cause our Epic Marketplace submissions to start failing because cesium-native is built against the wrong xcode. In the latter case... I guess we'll have to figure something out.
> Use xcode 12, cause the travis 11.3 doesn't work anymore.

- CHANGES.md
- Source/CesiumRuntime/Private/Cesium3DTileset.cpp
- Source/CesiumRuntime/Private/CesiumGltfComponent.cpp
- Source/CesiumRuntime/Private/CesiumGltfComponent.h
- Source/CesiumRuntime/Public/Cesium3DTileset.h
- Source/CesiumRuntime/Public/CustomDepthParameters.h
UE4 has a pretty handy custom depth buffer and stencil buffer. They're settings available on any primitive component, but so far it hasn't been exposed to the Cesium3DTileset actor. I added this setting and passed it to the `GltfComponent` so it gets applied when creating the `GltfPrimitiveComponent`.
I figured that setting it on creation would be a better idea than setting it on Tick (even though the engine calls do check if there's a change before marking the component's render state dirty) because of the number of components that might exist in a scene, and I would doubt that users would need to change it at runtime.
To test this feature, you will need to configure the project to support Custom Depth, or Custom Depth with Stencil if you want to test out the stencil feature. Here's a …
> Added custom depth and stencil support to Cesium3DTileset

- extern/.vscode/settings.json
Without this, Intellisense doesn't work on my system for cesium-native opened on the extern directory. It shows red squiggles for most `#include` lines because it apparently can't resolve the include directory. It used to work, so I'm not sure what changed, but we already have this setting in cesium-native itself and there should be no harm in adding it here, too.
> Set C_Cpp.default.configurationProvider VSCode setting.

- CHANGES.md
- Source/CesiumRuntime/Private/Cesium3DTileset.cpp
- Source/CesiumRuntime/Private/CesiumGltfComponent.cpp
- Source/CesiumRuntime/Private/CesiumGltfComponent.h
- Source/CesiumRuntime/Private/CesiumGltfPrimitiveComponent.cpp
- Source/CesiumRuntime/Private/CesiumGltfPrimitiveComponent.h
- Source/CesiumRuntime/Private/CesiumLifetime.cpp
- Source/CesiumRuntime/Private/CesiumLifetime.h
When a 3D Tiles tile is no longer needed, cesium-native tells Cesium for Unreal to unload it. We call `DestroyComponent` on the tile's `UCesiumGltfComponent` as well as any `UCesiumGltfPrimitiveComponent`s. But unfortunately (and surprisingly) this leaves all the texture and mesh data in memory until the garbage collector runs. And when we're running in the Editor, the garbage collector isn't run at all, so the resources never get freed! 😱 It doesn't take long flying around a big photogrammetry model to run out of memory and crash this way.
The reason that destroying the component doesn't destroy the corresponding meshes and textures is that meshes and textures are UObject's, and they're allowed to be shared between components. There's no ownership or reference counting, only the garbage …
> Manually release tile resources when the tile is unloaded

- .travis.yml
- Source/CesiumRuntime/Private/Cesium3DTileset.cpp
- Source/CesiumRuntime/Private/CesiumBingMapsRasterOverlay.cpp
- Source/CesiumRuntime/Private/CesiumIonRasterOverlay.cpp
- Source/CesiumRuntime/Private/CesiumPolygonRasterOverlay.cpp
- Source/CesiumRuntime/Private/CesiumRasterOverlay.cpp
- Source/CesiumRuntime/Private/CesiumTileMapServiceRasterOverlay.cpp
- Source/CesiumRuntime/Public/CesiumBingMapsRasterOverlay.h
- Source/CesiumRuntime/Public/CesiumIonRasterOverlay.h
- Source/CesiumRuntime/Public/CesiumPolygonRasterOverlay.h
- Source/CesiumRuntime/Public/CesiumRasterOverlay.h
- Source/CesiumRuntime/Public/CesiumTileMapServiceRasterOverlay.h
Most importantly the screen-space error, which is now independent of the geometry SSE.
Requires CesiumGS/cesium-native#327.
> Make raster overlay options configurable.

- Source/CesiumRuntime/Private/CesiumGltfComponent.cpp
Fixes #674 
It's not needed in all (most?) scenarios, but should be here regardless.
> Add missing #include.

- CHANGES.md
- Source/CesiumRuntime/Private/GlobeAwareDefaultPawn.cpp
`GlobeAwareDefaultPawn` completely ignores requests to do camera flights that have "zero steps" as defined by  its `FlyToGranularityDegrees` property. With this PR, it will do arbitrarily short flights, including rotation-only flights.
Fixes #678
> Allow short camera flights.

- CHANGES.md
- Source/CesiumRuntime/Private/Cesium3DTileset.cpp
- Source/CesiumRuntime/Private/CesiumDebugColorizeTilesRasterOverlay.cpp
- Source/CesiumRuntime/Public/Cesium3DTileset.h
- Source/CesiumRuntime/Public/CesiumDebugColorizeTilesRasterOverlay.h
- Added an ActorComponent for the tile colorizing raster overlay added in https://github.com/CesiumGS/cesium-native/pull/396
- Added a new option "Log Selection Stats" to the debug section of the Cesium3DTileset Actor. When enabled, stats about the tile selection process are printed to the output log with `Display` level. Previously these were always logged but effectively never seen because they were printed with the `VeryVerbose` level.
> Add a tile colorizer and an option to output selection stats.

- .travis.yml
Epic reported problems building our latest release on macOS:
```
Undefined symbols for architecture x86_64:
"___darwin_check_fd_set_overflow", referenced from:
httplib::detail::SocketStream::is_readable() const in libCesiumIonClient.a(Connection.cpp.o)
httplib::detail::SocketStream::is_writable() const in libCesiumIonClient.a(Connection.cpp.o)
httplib::detail::keep_alive(int, long) in libCesiumIonClient.a(Connection.cpp.o)
httplib::Server::listen_internal() in libCesiumIonClient.a(Connection.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
This is almost certainly caused by our move to xcode 12 in #682. This PR goes back to xcode 11.3 and then solves the original problem by removing the use of …
> Go back to xcode 11.3 (instead of 12)

- CHANGES.md
- Source/CesiumRuntime/Private/Cesium3DTileset.cpp
- Source/CesiumRuntime/Public/Cesium3DTileset.h
This fixes part of #680.
If an Editor viewport is viewing a particular camera, and that camera specifies an aspect ratio that doesn't match the dimensions of the viewport window, Unreal draws black bars at the sides or at the top and bottom, i.e. letterboxing. No real surprise there, of course.
The perhaps more surprising thing is that `FEditorViewportClient::GetViewportDimensions` returns the size of the complete window, not the size of the portion in which rendering occurs. That is, the black bars are included in the size.
Having not realized or appreciated this, we were using the window dimensions for LOD computations, and computing the vertical FOV from the aspect ratio implied by the window dimensions. This caused LOD and culling problems, as seen in #680.
So with this PR, we use the …
> Handle viewport aspect ratio not matching viewport dimensions.

- CesiumForUnreal.uplugin
There are two spaces in between `EngineVersion` and `4.26.0` in the uplugin file. As a result, the travis pipeline for 4.27 https://github.com/CesiumGS/cesium-unreal/blob/main/.travis.yml#L65 should break at the point where it does an in-place edit from `4.26.0` to `4.27.0`. Perhaps builds are still getting created despite this, but when running that command locally, the `sed` command doesn't succeed.
> Removed extra space from engine version in .uplugin

- CHANGES.md
- Source/CesiumRuntime/Private/CesiumGeoreference.cpp
> Fixes crash when editing georeference while sublevel is selected

- CHANGES.md
- Source/CesiumRuntime/Private/Cesium3DTileset.cpp
- Source/CesiumRuntime/Private/CesiumCamera.cpp
- Source/CesiumRuntime/Private/CesiumCameraManager.cpp
- Source/CesiumRuntime/Public/Cesium3DTileset.h
- Source/CesiumRuntime/Public/CesiumCamera.h
- Source/CesiumRuntime/Public/CesiumCameraManager.h
Custom camera views into Cesium tilesets that aren't automatically picked up can be manually registered now through Blueprint or C++. Extra views can be programmatically updated each frame, in the example below the custom view simply sweeps 360 degrees. This custom camera registration ability may also be useful for AI that needs to "probe" certain sections of tileset geometry to navigate.
> Blueprint API for Registering Custom Cameras

- Source/CesiumRuntime/Public/CesiumCamera.h
This should fix the CI in main. This was only caught in the IOS and Mac 4.27 CI, which didn't exist in #459. So merging that PR into main must have broken CI.
> Added missing category specifiers in CesiumCamera

- CHANGES.md
- CesiumForUnreal.uplugin
- Source/CesiumRuntime/Private/Cesium3DTileset.cpp
- package.json
#713 made a seemingly sensible change to where the request cache is stored on Android devices. But after that change, apps that use Cesium for Unreal crash on startup on Android. On my phone, the cache filename ends up being `../../../CesiumForUnrealSamples/Saved/Cesium/cesium-request-cache.sqlite`. That sure looks like a relative path to me, despite the fact that it's the result of calling `ConvertToAbsolutePathForExternalAppForWrite` 🤷. My guess is that it's relative to the wrong place or somesuch, so Android won't let us open a file for writing there.
This PR switches back to the previous location on Android. It continues to use the new one on iOS.
> Revert change to Android cache DB location

- CHANGES.md
- Source/CesiumEditor/Private/CesiumEditor.cpp
- Source/CesiumRuntime/Private/CesiumIonRasterOverlay.cpp
- Source/CesiumRuntime/Private/CesiumRasterOverlay.cpp
Fixes #755 
There's more we could do here, but this fixes the most important part by far. With this PR, the Token Troubleshooting panel will no longer appear when in Play-In-Editor (or any other game world). And we'll no longer try to connect to ion and pop up a troubleshooting panel for an asset ID of 0.
> No troubleshooting panel in game worlds

- Source/CesiumRuntime/Private/CesiumTextureUtility.cpp
This is a small PR to make sure `ImageCesiumMipPosition`s point to valid pixels before trying to read from potentially invalid memory.
> Verify mips point to valid pixels.

- Source/CesiumRuntime/Private/Cesium3DTileset.cpp
- Source/CesiumRuntime/Private/CesiumGltfComponent.cpp
- Source/CesiumRuntime/Private/CesiumGltfComponent.h
- Source/CesiumRuntime/Private/CesiumGltfPrimitiveComponent.cpp
- Source/CesiumRuntime/Private/CreateModelOptions.h
- Source/CesiumRuntime/Private/LoadModelResult.h
- package-lock.json
Attempts to slightly clean up the hierarchical glTF loading in `CesiumGltfComponent.cpp`. The main goal is to make gltf loading more easily extensible as we grow support for extensions. Hopefully this means future changes / additions to the gltf loading process can be more localized to only the functionality and hierarchy level that they effect.
Main Changes:
- `CreateModelOptions` replaced by several structs for model options, node options, mesh options, and primitive options. Each struct can be extended easily in the future to contain new options (usually from glTF extensions) at that level. For example, nodes usually have a single mesh, but with the MAXAR_mesh_variants extension, an arbitrary number of meshes may be associated with a node. Similarly, in EXT_mesh_gpu_instancing, the …
> Refactor CesiumGltfComponent.cpp

- Source/CesiumRuntime/Private/CesiumGeoreference.cpp
- Source/CesiumRuntime/Private/CesiumGltfComponent.cpp
* Some APIs have changed from variables to getter/setters.
* I'm not sure why UE5 build tool is not detecting `ChaosDerivedDataUtil.h`, but that header has a single function which we are not using. So maybe we can remove it from the UE4 version as well.
* There is one warning remaining
```
[9/13] Module.CesiumRuntime.cpp
C:/Users/smohammed/workspace/PackagesUE5/CesiumForUnreal/HostProject/Plugins/CesiumForUnreal/Source/CesiumRuntime/Private/CesiumGltfComponent.cpp(1448): warning C4996: 'UStaticMesh::SetIsBuiltAtRuntime': SetIsBuiltAtRuntime() is no longer used. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
```
But this is weird because UE5 removed the `bIsBuiltAtRuntime` variable, changed it into a const get …
> UE5 Compilation Support

- Source/CesiumRuntime/Private/CesiumGltfComponent.cpp
Prior to #129, we sometimes had a crashing at shutdown or when switching levels causes by attempting to modify material parameters while the material was being destroyed. I fixed it by checking `Material->IsPendingKillOrUnreachable()` before attempting to modify parameters. But UE5 doesn't have this method, so in #735 I replaced with with a simple `IsValid`. That's not the same thing, and caused the crash bug to come back. So this PR switches back to `IsPendingKillOrUnreachable` in UE4, avoiding the regression. There are likely still problems in UE5.
> Check IsPendingKillOrUnreachable before modifying materials.

- Source/CesiumRuntime/Private/Cesium3DTileset.cpp
- Source/CesiumRuntime/Private/CesiumGltfComponent.cpp
- Source/CesiumRuntime/Private/CesiumGltfComponent.h
- Source/CesiumRuntime/Private/CesiumTextureUtility.cpp
- Source/CesiumRuntime/Private/CesiumTextureUtility.h
- Source/CesiumRuntime/Private/LoadModelResult.h
- Source/CesiumRuntime/Public/Cesium3DTileset.h
This prevents the leak where loaded result from worker thread is getting deleted in the main thread, but doesn't delete any sub resources. The bug can be reproduced by tuning the cache down to 0 and enabling ancestor and sibling preloading options. To make sure it's not the garbage collection being idle, you can use the command `gc.CollectGarbageEveryFrame 1`. You can see the memory increase after about 15 or 20 minutes of moving around. It happens more frequently with larger tileset.
To track the memory, you can run the sample with `-LLM` in the visual studio command line options. Then, in the editor, use command `stat LLM` in the console to see the memory
> Manage FStruct with TUniquePtr instead of raw pointer

- .concierge/config.json
- .concierge/templates/pullRequestOpened.hbs
Cesium Concierge now supports checking GitHub's contributor list for new and existing contributors. This PR adds this check and adds a welcome message for 1st time contributors.
> Add concierge config to check first time contributors.

- CesiumForUnreal.uplugin
- Source/CesiumRuntime/CesiumRuntime.Build.cs
- Source/CesiumRuntime/Private/CesiumEncodedMetadataComponent.cpp
- Source/CesiumRuntime/Public/CesiumEncodedMetadataComponent.h
- Source/CesiumRuntime/Public/CesiumExclusionZone.h
- Source/CesiumRuntime/Public/CesiumMetadataFeatureTable.h
This is a PR into #698. The reason Travis CI fails in that branch is because our dodgy cut down distribution of Unreal Engine doesn't include a bunch of plugins, including EditorScriptingUtilities. But it's relatively easy to remove the dependency in this case, so that's what I've done.
I also removed the code that saves the generated material. I think it's fine to let the Editor consider it unsaved, and to let the user save in the normal way if they would like to do so. But maybe there's a more subtle reason it was necessary to save it explicitly? Everything seemed to work ok, but it's possible I missed something.
> Remove dependency on EditorScriptingUtilities plugin in the metadata-textures branch

- CHANGES.md
- Source/CesiumRuntime/Private/Cesium3DTileset.cpp
- Source/CesiumRuntime/Private/CesiumGltfComponent.cpp
- Source/CesiumRuntime/Private/CesiumGltfComponent.h
- Source/CesiumRuntime/Private/CesiumGltfPrimitiveComponent.cpp
- Source/CesiumRuntime/Private/CesiumGltfPrimitiveComponent.h
When we create a static mesh, we must provide an AABB and bounding sphere. These bounding volumes aren't used for culling or tile selection in cesium-native, because it has its own (more accurate) bounding volumes, but Unreal Engine uses them for its own frustum and occlusion culling and possibly other things.
The AABB is provided in model coordinates, and then it's transformed into world coordinates as the static mesh component's transformation changes. The problem is that our tile models are often expressed in ECEF (minus a translation), and so they're really poorly aligned with the axes. Therefore, our AABBs, when expressed in model coordinates, are big and cube-like. Once they're rotated into world coordinates, the CesiumGeoreference guarantees that tiles near the origin are _much_ …
> Compute much better axis-aligned bounding boxes for tiles, for use by Unreal Engine

- Source/CesiumRuntime/Private/Cesium3DTileset.cpp
> Stop encoding metadata after deleting metadata component

- CHANGES.md
- Source/CesiumRuntime/Private/CesiumGltfPrimitiveComponent.cpp
Fixes #839
I "improved" the bounding box computation in #823. It looked surprisingly right considering how actually wrong it was. 😆
Generally it worked ok near the georeference origin, but got very bad for tiles that are not well aligned to the Unreal axes.
I think it's correct now, but it would definitely be wise for someone to double-check my math when reviewing this!
> Fix incorrect computation of bounding boxes

- CHANGES.md
- Source/CesiumRuntime/Private/CesiumGltfComponent.cpp
Fixes #717 
When you drag/drop a material on a tileset in the viewport, Unreal applies that material to all of the actor's static meshes. This is not very useful because Cesium for Unreal creates new static meshes all the time, and it won't use that new material when it does so. So basically the material change is just temporary.
However, if you then set the material property on the Tileset itself, our code will try to destroy the old Material. And it does so in such a way that if the old material that was applied to a static mesh isn't derived from `UMaterialInstanceDynamic` (as ours are), it will end up dereferencing a nullptr and crash.
So this PR simply guards against the crash. I looked briefly into what it would take to make dragging/dropping a material properly apply the material …
> Don't crash when destroying a material that isn't the right type

- Documentation/developer-setup-windows.md
As reported on the community forum:
https://community.cesium.com/t/development-setup/16792
Our setup instructions say to look in the Visual Studio Solution Explorer for a folder called `CMakePredefinedTargets`. But that doesn't seem to exist anymore, probably as a result of a newer version of either Visual Studio 2019 or CMake. Instead, the INSTALL target is just sitting at the top level. So I updated the instructions accordingly.
> Update developer setup instructions to look for INSTALL at the root.

- .github/workflows/build.yml
I've enabled the [runner_enable_workflow_job_labels_check](https://github.com/philips-labs/terraform-aws-github-runner#input_runner_enable_workflow_job_labels_check) option in our self-hosted Actions runner config so that it won't spin up new EC2 instances for builds that don't need the self-hosted runner (i.e. macOS, iOS, Combine). But with that option enabled, the set of labels has to match exactly. So this PR adds the necessary labels.
> Use proper labels for self-hosted runners.

- .travis.yml
Moves package upload to after_success. So we don't fill up S3 with broken builds. Because of the way the UE
build process works, failed plugin builds are much larger than successful ones.
> Don't publish broken builds.

- .github/workflows/build.yml
Same as #854 but for UE5 / GitHub Actions.
> Don't create artifacts for broken UE5 builds

- CHANGES.md
- Config/Engine.ini
- Source/CesiumRuntime/Private/CesiumPolygonRasterOverlay.cpp
- Source/CesiumRuntime/Public/CesiumPolygonRasterOverlay.h
Exposes the new option to invert polygon selections added in Cesium Native here, merge it first: https://github.com/CesiumGS/cesium-native/pull/504
> Add option to invert CesiumPolygonRasterOverlays

- CHANGES.md
- Source/CesiumRuntime/Public/CesiumGeoreference.h
- Source/CesiumRuntime/Public/CesiumSubLevel.h
Contains a few small fixes to the editor UI for georeferenced sublevels.
- Swapped the latitude and longitude parameter of sublevels in the array so that they match the latitude/longitude standard. (Tested this in editor and the change did not seem to introduce any issues.)
- Recategorized the sublevel-related parameters on the CesiumGeoreference so that the sublevels category is nested under the "Cesium" category and not as a separate category
- Changed the display name of the `CesiumSubLevels` array to read "Georeferenced Sublevels". This is for clarity and consistency of documentation. Since the property name itself is unchanged, this should not be a breaking change.
Old on left, new on right.
<p>
<br/>
I wasn't sure if the sublevel parameters had been in their own category for a …
> Sublevel property cleanup

- CHANGES.md
- Source/CesiumRuntime/Private/CesiumLifetime.cpp
Starting in v1.13.0, panning around the Melbourne example level in the Editor causes memory usage to grow without bound. I eventually tracked it down the cause: starting in v1.13.0, we're asking PhysX to `bSupportUVFromHitResults` and `bSupportFaceRemap`. This causes it to produce a bunch of extra data that we put into a `UBodySetup`. But when we free the `UBodySetup` in `CesiumLifetime`, we were failing to free this extra data. One might expect a method called `ClearPhysicsMeshes` (which we were already calling) to free this data, too, but alas, it does not.
Without the explicit free:
1) Memory usage grows without bound in the Editor, because the Editor doesn't run the UE garbage collector.
2) In-game, the garbage collector will free this memory eventually, but probably not as soon as …
> Explicitly free UBodySetup UVInfo and FaceMap data in CesiumLifetime

- CHANGES.md
- Source/CesiumRuntime/Private/Cesium3DTileset.cpp
- The original github issue #830 was a red herring, the problem wasn't that the wrong tileset was loaded, but it was a mistake on the log that printed out the wrong information about the source and tilset input url or ID.
> Update tile url source logs

- CHANGES.md
- Source/CesiumRuntime/Private/Cesium3DTileset.cpp
- Source/CesiumRuntime/Private/CesiumGltfComponent.cpp
- Source/CesiumRuntime/Private/CreateGltfOptions.h
- Solves #860 
- Adds a new field in `CreateGltfOptions` that indicates whether if we should create physics meshes for the Gltf
- Tested on UE5
> Disable physics mesh option in ue5 with Chaos

- CHANGES.md
- Source/CesiumEditor/Private/CesiumEditor.cpp
- Source/CesiumRuntime/Private/Cesium3DTileset.cpp
- Source/CesiumRuntime/Private/CesiumRasterOverlay.cpp
- Source/CesiumRuntime/Public/Cesium3DTilesetLoadFailureDetails.h
- Source/CesiumRuntime/Public/CesiumRasterOverlayLoadFailureDetails.h
Fixes #879 
Like Bao said in that issue, I don't completely understand why UE5 (only) is unloading the _new_ level and destroying its tilesets when switching levels. But whatever the reason (or even if it's a bug), the fact remains that it's _possible_ for a Tileset or RasterOverlay to be destroyed between the time we schedule a main thread task to handle a load error and the time that main thread task is actually run. And it's not ok to crash when that happens. So now the load error structs use `TWeakObjectPtr` to guarantee we don't dereference a stale pointer while handling load errors.
> Don't crash if a tileset/overlay is destroyed while reporting error.

- Source/CesiumRuntime/Private/CesiumCreditSystem.cpp
- Source/CesiumRuntime/Public/CesiumCreditSystem.h
Fixes #921 
_creditsWidget was null and caused the program to crash. Although I haven't been able to reproduce it, it was most likely deleted by the garbage collector because it wasn't a UPROPERTY. 
Also replaced nullptr checks for IsValid.
> Credits Crash

- Source/CesiumRuntime/Private/Cesium3DTileset.cpp
- Source/CesiumRuntime/Private/CesiumBoundingVolumeComponent.cpp
- Source/CesiumRuntime/Private/CesiumBoundingVolumeComponent.h
- Source/CesiumRuntime/Private/CesiumViewExtension.cpp
- Source/CesiumRuntime/Private/CesiumViewExtension.h
- Source/CesiumRuntime/Public/Cesium3DTileset.h
We are pretty sure that the current way that occlusion results are retrieved from the renderer is technically thread-unsafe (https://github.com/CesiumGS/cesium-unreal/issues/904). This attempts to fix that by retrieving occlusion results on the render thread.
Thanks to Kevin for suggesting this type of approach in [this comment](https://github.com/CesiumGS/cesium-unreal/pull/917#issuecomment-1191240481), this feels a lot safer and easier to reason about!
> Collect occlusion results on the render thread 

- Source/CesiumEditor/Private/CesiumEditor.cpp
- This PR removes calling `supportsRasterOverlay` which is removed in `cesium-native` in this PR: https://github.com/CesiumGS/cesium-native/pull/532
> Remove supportrasteroverlay

- CHANGES.md
- Source/CesiumRuntime/Private/ScreenCreditsWidget.cpp
SRichTextHyperlink didn't work the same way in UE5 and prevented images from showing. Instead changed to an SButton.
> Fix credit images not showing in UE5

- CHANGES.md
- Source/CesiumRuntime/Private/GlobeAwareDefaultPawn.cpp
- Source/CesiumRuntime/Public/GlobeAwareDefaultPawn.h
- Solves #827 
- Adds a BP accessible delegate `onFlightComplete` in the `AGlobeAwareDefaultPawn` class. 
- Tested with the `flyTo` example following the tutorial: https://cesium.com/learn/unreal/unreal-flyto/. 
- @nithinp7
> Add callback for when dynamic pawn finishes flying

- Source/CesiumRuntime/Private/CesiumBoundingVolumeComponent.cpp
- Source/CesiumRuntime/Private/CesiumBoundingVolumeComponent.h
- Source/CesiumRuntime/Private/CesiumViewExtension.cpp
- Source/CesiumRuntime/Private/CesiumViewExtension.h
Fixes #924. 
This turned out to be a very similar problem to the infamous flickering holes bug. It has to do with stale occlusion results for bounding volume proxies that are newly set to visible (ones that have been newly assigned to a tile). Particularly, when there was a bounding volume proxy that was previously occluded when assigned to a previous tile and then got unassigned and then much later reassigned to a new tile. The last occlusion result from the old tile assignment ended up being picked up and the selection mistakenly thinks the tile is occluded. The solution is to keep track of when a tile is assigned and ignore occlusion results from before the assignment.
> Fix 1-3 frame false-occlusion bug

- Source/CesiumRuntime/Private/Cesium3DTileset.cpp
- Source/CesiumRuntime/Public/Cesium3DTileset.h
- Source/CesiumRuntime/Public/CesiumRuntimeSettings.h
As mentioned in https://github.com/CesiumGS/cesium-unreal/pull/928#issuecomment-1200835178, this puts the occlusion culling feature behind a feature flag, which is found in Project Settings. The reason is:
1. I'm nervous to have occlusion culling "on by default" currently given the deep renderer integration and last-minute changes. While it's working well in our tests, it wouldn't be surprising to run into issues on some platforms or in some environments, or even to run into visual artifacts with certain tilesets in certain cases.
2. If we do the simple thing of just defaulting the "Enable Occlusion Culling" property on Cesium3DTileset to _off_, then later, when we do want it to be on by default, people with existing levels will need to re-enable it manually. We won't be able to easily …
> Put occlusion culling behind a feature flag.

- CHANGES.md
- Source/CesiumRuntime/Private/Cesium3DTileset.cpp
- Source/CesiumRuntime/Private/CesiumViewExtension.cpp
- Source/CesiumRuntime/Private/CesiumViewExtension.h
This PR fixes a crash in UE5 when opening the Project Settings panel. It's caused by a `FSceneView` having a nullptr `State`, which can apparently (according to a comment above the field) happen when the view is used for thumbnail rendering.
It also "fixes" (very much in quotes) a crash at startup in UE4.26. The crash happens when we try to copy the `PrimitiveOcclusionHistorySet`, and it may actually be a 4.26 bug. What I've done here is to more fully disable the `CesiumViewExtension` when the Occlusion Culling feature is disabled. This way the crash doesn't happen at startup, but instead happens when the user tries to enable the experimental occlusion culling feature. Disabling the CesiumViewExtension is a good idea anyway, to reduce the chances of problems caused by our interaction with …
> Occlusion culling: handle nullptr State, disable the CesiumViewExtension when the feature is disabled

- CHANGES.md
- Source/CesiumRuntime/Private/Cesium3DTileset.cpp
Now only viewports that are visible, real-time, and use a perspective projection are used for tile selection.
This is especially important in UE5 because collapsed Editor viewports seem to no longer get a 0,0 size in that version.
Probably the most controversial one here is the "visible", because Unreal considers all viewports non-visible if another application (other than the UE Editor) has the focus. That effectively means tile selection will stop when the Editor loses focus. I think we can live with this, though, especially since I wasn't able to find a better alternative.
Fixes #801
> Don't use dodgy Editor viewports.

- Source/CesiumEditor/Private/CesiumSourceControl.cpp
Changed `#include "HAL/PlatformFilemanager.h"` to `#include "HAL/PlatformFileManager.h"` inline with Unreal Engine 5's name change
Related Issue: #953
> Fixed PlatformFileManager naming

- CHANGES.md
- Source/CesiumRuntime/Private/CesiumGltfComponent.cpp
Fixes #900
When setting the Chaos triangles, the indices are set to uint16 if the number of vertices is less than 65536, and int32 otherwise.
However, for some reason, adding uint16 triangles causes the issue. 
In the Unreal Code, https://github.com/EpicGames/UnrealEngine/blob/release/Engine/Source/Runtime/Engine/Private/PhysicsEngine/Experimental/ChaosCooking.cpp#L302, they also create an array of uint16 triangles, however in the lamba function, they add int32 triangles to it (https://github.com/EpicGames/UnrealEngine/blob/release/Engine/Source/Runtime/Engine/Private/PhysicsEngine/Experimental/ChaosCooking.cpp#L254).
This PR changes the code to do the same thing.
> Fix UE5 Line Tracing bug

- CHANGES.md
- Source/CesiumRuntime/Private/Cesium3DTileset.cpp
This PR fixes the problem where pressing ALT and the drag left mouse button in the Editor viewport causes tiles to disappear.
> Fix disappearing tiles when camera is orbiting

- Source/CesiumRuntime/Private/CesiumCreditSystem.cpp
When trying to run CesiumForUnreal inside a dedicated server it will crash after trying to add the widget to the viewport. 
https://github.com/CesiumGS/cesium-unreal/issues/931
> Prevent dedicated server from adding a ScreenCreditWidget.

- CHANGES.md
- Source/CesiumRuntime/Private/CesiumGltfComponent.cpp
Fixes #874
We need to copy texture coordinates for all three types, Feature Textures, Feature ID textures and Feature ID attributes. 
An easy way to tell if a model/primitive may need the UV data is if ```metadataTextureCoordinateParameters``` is not empty.
TODO: Only copy the UV channels associated with metadata.
> Copy UV data to physics mesh only when using metadata textures

- Documentation/release-process.md
It's best to wait until after Epic has accepted and published the updated plugin.
> Add a note about when to publish the samples project

- CHANGES.md
- Source/CesiumRuntime/Private/Cesium3DTileset.cpp
Fixes #742 . This PR modifies `applyActorCollisionSettings` such that the function iterates over all of the `UCesiumGltfComponent`'s children and applies the setting.
> Make tilesets apply collision settings to all glTF primitives

- Documentation/developer-setup-linux.md
This workflow has been tested on Ubuntu 20.04.3 LTS with UE 5.0.3. It may not fix all issues encountered with compiling Cesium-Unreal on Linux, but it also fixes several obvious out of date instructions.
Based on troubleshooting done in #955
> Updated UE5 Linux setup documentation

- CHANGES.md
- Source/CesiumRuntime/Private/ScreenCreditsWidget.cpp
Fixes #967
The problem was naming collision, both decorators had the name `FRichInlineImage`. By renaming it to `FScreenCreditsDecorator` fixed the issue.
> Fix Rich Text Block image decorators not showing

- CHANGES.md
- Source/CesiumRuntime/Private/Cesium3DTileset.cpp
- Source/CesiumRuntime/Private/CesiumGltfComponent.cpp
- Source/CesiumRuntime/Private/CesiumGltfPrimitiveComponent.cpp
- Source/CesiumRuntime/Public/Cesium3DTileset.h
We recently changed the components in Cesium3DTilesets to have static mobility (previously they were movable), allowing for several optimizations in the engine. In certain use cases however, it may still be useful to have a movable tileset. This PR adds an option in the Cesium3DTileset details panel to change the default mobility.
Fixes #970
> Add option to change mobility

- CHANGES.md
- Source/CesiumRuntime/Private/CesiumCreditSystem.cpp
- Source/CesiumRuntime/Public/CesiumCreditSystem.h
This is useful for Project Anywhere XR so that the credits can be displayed on an in-game 3D billboard, rather than as a 2D overlay on the screen. CC @AlbanBERGERET-Epic
> Make credit system's widget publicly accessible.

- Source/CesiumRuntime/Public/CesiumSunSky.h
Made the following variables public so they can be edited from other classes:
- TimeZone
- SolarTime
- Day, Month, Year
- NorthOffset
- UseDaylightSavingsTime
The goal was to make the SunSky flexible so that as the user travels around different parts of the globe, the time settings can change accordingly.
> Make CesiumSunSky member variables public

- CHANGES.md
- Source/CesiumRuntime/Private/CesiumGeoreference.cpp
- Source/CesiumRuntime/Private/GeoTransforms.cpp
- Source/CesiumRuntime/Private/GlobeAwareDefaultPawn.cpp
- Source/CesiumRuntime/Private/VecMath.cpp
- Source/CesiumRuntime/Private/VecMath.h
- Source/CesiumRuntime/Public/CesiumGeoreference.h
- Source/CesiumRuntime/Public/GeoTransforms.h
Somewhat related to #265 and #733.
I think our East-North-Up <--> Unreal conversion functions in the Georeferencing API are quite broken. This PR attempts to fix some if not all of it. 
We had functions to transform rotators (pitch, yaw, roll) from ENU to Unreal and vice-versa. These were implemented by:
Step 1: Convert FRotators (pitch, yaw, roll) into quaternions.
Step 2: Compute the Unreal <--> ENU matrix and convert the rotation part into a quaternion.
Step 3: And then multiply the above two quaternions to transform a rotation between Unreal and ENU.
Step 4: And of course convert back from quaternion to pitch, yaw, roll at the end in the destination coordinate system.
Implementation mistakes fixed:
- There was a glaring mistake (made by me!) that flipped the direction of conversions …
> Fix broken euler angles and quaternion conversions

- Source/CesiumRuntime/Private/Cesium3DTileset.cpp
In function ACesium3DTileset::ResolveGeoreference(), OnGeoreferenceUpdated(delegate) binds to CesiumTileset's RootComponent;
`this->ResolvedGeoreference->OnGeoreferenceUpdated.AddUniqueDynamic(
pRoot,
&UCesium3DTilesetRoot::HandleGeoreferenceUpdated);`
However, in function ACesium3DTileset::InvalidateResolvedGeoreference(), OnGeoreferenceUpdated unbinds from Cesium3DTileset.
`this->ResolvedGeoreference->OnGeoreferenceUpdated.RemoveAll(this);`
This may cause unexpected problems in Cesium3DTileset when changing georeference.
By the way, this problem also exists in ue5 related branches.
> Fix UE delegate removal error in ResolvedGeoreference->OnGeoreferenceUpdated

- Source/CesiumRuntime/CesiumRuntime.Build.cs
- Source/CesiumRuntime/Private/Cesium3DTileset.cpp
- Added Renderer as a private include path
- included `LevelSequencePlayer.h` inside `Cesium3DTileset.cpp`
- Successfully packaged on Linux for Linux using RunUAT.sh
- Successfully packaged on Windows for Windows in UE5.1 Editor
**Fixes**:
- #1000
- Issue mentioned [here](https://community.cesium.com/t/cesium-for-ue-5-1/21093/11)
> Added Renderer as a private include path

- Source/CesiumRuntime/Private/CesiumTextureUtility.cpp
Hopefully this is a workaround for #1007, although it would be slightly better to get the current texture creation path to work for mac and linux. Both the Vulkan and Metal RHI implementations in Unreal do not have async texture creation implemented, so the current texture creation path on these platforms does the next best thing by avoiding a texture memcpy on the game thread (by wrapping the source texture memory into an Unreal-specific interface for direct GPU upload). But it won't be a huge loss to go back to the legacy texture creation code paths on these platforms.
TODO:
- Do we need to hardcode any other platforms to use the legacy code path, Android maybe?
> Use legacy texture creation for mac and linux

- .github/workflows/build.yml
UE 5.1 seems to have [a bug](https://forums.unrealengine.com/t/5-1-missing-precompiled-manifest-error-when-building-code-plugin-for-android/691983) that prevents packaging plugins for Android. I worked around this by moving some files around in the  UE directory. That allows us to package the plugin for Android successfully, but unfortunately when we later try to package a _game_ using that plugin, we get errors. These errors are basically the opposite of the errors during plugin packaging: the plugin includes an `arm64` directory and the game packaging doesn't expect it. So this PR adds a step to hack up the plugin after it's packaged so that it will later work at game package time.
> Fix Android game package failure in UE 5.1

- CHANGES.md
- Source/CesiumRuntime/Private/CesiumGeoreference.cpp
As reported here:
https://community.cesium.com/t/sublevels-in-ue5-broken/21475/5
> Fix flipped longitude/latitude on newly-created sub-levels.

- CHANGES.md
- Source/CesiumRuntime/CesiumRuntime.Build.cs
This is necessary because, at least in some cases, we `#include` headers from these modules in our own public headers. If these modules aren't declared public, projects that try to include our headers will get compiler errors unless they explicitly depend on the necessary modules.
See:
https://community.cesium.com/t/unable-to-package-ue5-0-3-project-with-cesium-v1-19-0/21162
> Declare UE modules as public dependencies, not private

- .github/workflows/build.yml
- CHANGES.md
- Source/CesiumRuntime/Private/CesiumMaterialUserData.cpp
UE 5.1 introduced breaking changes in how we obtain the names of material layers. I updated the code to compile, but didn't realize that the "Layer Name" I was now accessing was actually the name of the material layer _asset_, not the name of the material layer itself. So, for example, for this layer:
we wanted to get `Overlay0`, but in UE 5.1 we were instead getting `ML_CesiumRasterOverlay`.
Because various material parameters are assigned based on these names, Cesium materials pretty much completely stopped working in UE 5.1. This was most obvious for tilesets with raster overlays, which would just appear white.
You might wonder how this went unnoticed. Well, as long as the material was last saved in a _previous_ version of Unreal Engine, it worked fine even in UE 5.1. It was only if we …
> Fix broken materials in Unreal Engine 5.1

- Source/CesiumRuntime/Private/CesiumGltfComponent.cpp
This is #1036 rebased on `ue4-main`. I also tweaked the comment and organization of the code slightly.
> Rebase "Configure tile static meshes to use full-precision UVs" on ue4-main

- CHANGES.md
- Source/CesiumRuntime/Private/CesiumGltfComponent.cpp
- Source/CesiumRuntime/Private/CesiumGltfPointsComponent.cpp
- Source/CesiumRuntime/Private/CesiumGltfPointsComponent.h
- Source/CesiumRuntime/Private/CesiumGltfPrimitiveComponent.cpp
- Source/CesiumRuntime/Public/Cesium3DTileset.h
This PR adds support for rendering glTFs with point primitives in Cesium for Unreal. It's mostly done, but it needs tweaks and more thorough testing.
**TODO:**
> Add support for rendering points

- CHANGES.md
- Source/CesiumEditor/Private/SelectCesiumIonToken.cpp
Fixes #1042. The problem was that a main thread task is calling Destroy Tileset. The tileset would destroy itself when calling dispatch main thread tasks.
> Fix crash when changing project default token

- CHANGES.md
- Source/CesiumRuntime/Private/Cesium3DTileset.cpp
- Source/CesiumRuntime/Private/CesiumGeoreference.cpp
- Source/CesiumRuntime/Private/CesiumGltfComponent.cpp
- Source/CesiumRuntime/Private/CesiumLifetime.cpp
- Source/CesiumRuntime/Private/CesiumRasterOverlay.cpp
- Source/CesiumRuntime/Private/GeoTransforms.cpp
- Source/CesiumRuntime/Private/GlobeAwareDefaultPawn.cpp
- Source/CesiumRuntime/Private/ScreenCreditsWidget.cpp
- Source/CesiumRuntime/Private/VecMath.cpp
- Source/CesiumRuntime/Public/CesiumRuntime.h
I also tried compiling the plugin without the normal unity builds enabled, and found a few missing headers, which I added. See #615 for how that works.
I'm going to self merge this as there is no change in functionality.
> Update for breaking changes in cesium-native

- CHANGES.md
- Source/CesiumRuntime/Public/GlobeAwareDefaultPawn.h
Fixes #1052 
https://community.cesium.com/t/transition-between-more-than-one-geo-marker/22612
> adds the BlueprintReadWrite property specifier to GlobeAwareDefaultPawn FlyTo variables

- Source/CesiumRuntime/Private/GlobeAwareDefaultPawn.cpp
- Source/CesiumRuntime/Public/GlobeAwareDefaultPawn.h
I was a little too quick to merge #1059. It doesn't work in UE4 because properties of type double cannot be accessible from Blueprints. This PR changes the problematic properties, `FlyToDuration` and `FlyToGranularityDegrees`, to floats instead of doubles. This change shouldn't make any difference from a precision perspective, because these properties will have relatively small numbers that don't need to be extraordinarily precise.
> Fix errors caused by blueprint-accessible doubles.

- CHANGES.md
- Source/CesiumRuntime/Private/Cesium3DTileset.cpp
- Source/CesiumRuntime/Private/CesiumGltfComponent.cpp
- Source/CesiumRuntime/Private/CesiumGltfComponent.h
- Source/CesiumRuntime/Public/Cesium3DTileset.h
- Source/CesiumRuntime/Public/CesiumRuntimeSettings.h
This PR accommodates #327. The latest version(v1.22.0) of Cesium for Unreal can not generate a NavMesh for a Cesium3DTileset
actor. However, this PR make it possible to generate a NavMesh on a Cesium3DTileset actor.
We have confirmed that NavMesh is generated after our modification using the "New York City 3D Buildings" asset provided by
Cesium Ion. The first image is before our modification and the second image is after our modification.
BeforeNavCollision
AfterNavCollision
> Generate navigation mesh on Cesium3DTileset

- Source/CesiumRuntime/Private/CesiumCreditSystem.cpp
This PR includes small cosmetic changes to the credit system.
1. Credits that are on-screen are now exclusively shown on screen, instead of both the screen and popup display.
2. The "Data Attribution" link is not included if there are no credits to be shown in the popup display.
> Properly separate on-screen credits from popup

- Source/CesiumRuntime/CesiumRuntime.Build.cs
We're getting warnings in  `\Plugins\CesiumForUnreal\Source\CesiumRuntime\CesiumRuntime.Build.cs(179,13)` that say `'ReadOnlyTargetRules.bCompilePhysX' is obsolete: 'Deprecated in UE5.1 - No longer used as Chaos is always enabled.'` This PR removes that check from the file.
@kring can you check if this is correct?
> Remove compilation of PhysX

- Source/CesiumRuntime/Private/CesiumCartographicPolygon.cpp
Missing calling `Super::BeginPlay()` in `ACartographicPolygon::BeginPlay()` causes we cannot destroy an `ACartographicPolygon` actor at runtime. Because before destroy the actor, we will check the actor `AActor::ActorHasBegunPlay` state. If the value is `EActorBeginPlayState::HasBegunPlay`, the actor will be mark pending killing. But `AActor::ActorHasBegunPlay` will be set to `EActorBeginPlayState::HasBegunPlay` in `AActor::BeginPlay()`.
> Fix for failed to destroy cartographic polygon at runtime

- Source/CesiumRuntime/Private/CesiumGltfPointsComponent.cpp
- Source/CesiumRuntime/Private/CesiumPointAttenuationVertexFactory.cpp
- Source/CesiumRuntime/Private/CesiumPointAttenuationVertexFactory.h
Just a proof of concept, but it does successfully make point cloud attenuation work on my old AMD GPU.
> Hacky fix for point cloud attenuation on AMD.

- CHANGES.md
- Source/CesiumRuntime/Private/CesiumGeoreference.cpp
- Source/CesiumRuntime/Private/CesiumMaterialUserData.cpp
- Source/CesiumRuntime/Private/CesiumSunSky.cpp
- Source/CesiumRuntime/Private/GeoTransforms.cpp
- Source/CesiumRuntime/Public/CesiumGeoreference.h
- Source/CesiumRuntime/Public/GeoTransforms.h
Unreal equivalent of CesiumGS/cesium-unity#303. Unlike in Unity, here the scale is a percentage (so 100 is full size). I did that because Unreal has a weird arbitrary limit on how small a number you enter on the details panel (after which it rounds to 0.0). So using a percentage lets us scale down by two more orders of magnitude.
Some problems I know about:
* The CesiumSunSky adjusts the SkyAtmosphere's radius to account for the globe scale. But other SkyAtmosphere parameters, like "Atmosphere Height", need to be adjusted manually for small scales or else the atmosphere will look totally wonky. And this parameter appears to have an arbitrary minimum value of 0.1. So you can't get a globe with a correct atmosphere at a smaller scale than 0.1% (0.001) or so.
* The Water Mask effect fades in …
> Add Scale property to CesiumGeoreference.

- Source/CesiumRuntime/Private/CesiumCreditSystem.cpp
- Source/CesiumRuntime/Private/CesiumCreditSystemBPLoader.h
- Source/CesiumRuntime/Public/CesiumCreditSystem.h
Fixes #1100 
It looks like the credits worked before because a Credits System was already in the Level and when a new Level was created, the code was not able to load the Blueprint class, perhaps because the class is not static. Loading it as an object instead of a class seems to fix the issue.
> Fix Credits Crash when creating new scene

- CHANGES.md
- Source/CesiumEditor/Private/CesiumEditor.cpp
- Source/CesiumEditor/Private/IonQuickAddPanel.cpp
- Source/CesiumRuntime/Private/CesiumEncodedMetadataComponent.cpp
- Source/CesiumRuntime/Private/CesiumGltfComponent.cpp
While playing around with World Partition, I ran into https://github.com/CesiumGS/cesium-unreal/issues/941, where the Editor crashes when attempting to unload a level with World Partition and a Cesium Actor. The crash is caused by Unreal attempting to CastChecked our Actor to UMetaData. Our Actor is not a UMetaData, so this checked cast fails, which is treated as a fatal error.
This cast happens inside [FWorldPartitionActorDesc::Unload](https://github.com/EpicGames/UnrealEngine/blob/5.2.0-release/Engine/Source/Runtime/Engine/Private/WorldPartition/WorldPartitionActorDesc.cpp#L605). Basically if the Actor `IsPackageExternal` (docs helpfully say "returns true if object has a different package than its outer's package"), and also it has the `RF_Public` or `RF_Standalone` flags, then it will …
> Fix World Partion crash by removing RF_Public

- Documentation/developer-setup-windows.md
Update pre-reqs section
- Move "Game development with C++" to its own line (easier to see)
- Removed options from VS setup (already included)
- C++ profiling tools
- C++ AddressSanitizer (optional)
- Windows 10 SDK (10.0.18362 or Newer)
- Add .NET Framework SDK (4.8) to installer. Needed to run "Generate Visual Studio project files" from right click context menu
- Add Install .NET core 3.1 Runtime. Same reason.
Clarify the section that builds cesium native under VS 2019
Clarify the section which converts the Unreal project to a C++ project
> Misc updates for Windows developer setup

- CHANGES.md
- Source/CesiumRuntime/Private/CesiumCreditSystem.cpp
- Source/CesiumRuntime/Public/CesiumCreditSystem.h
Move `::removeCreditsFromViewports` call out of `::BeginDestroy` and into `::EndPlay`. This prevents more work for the garbage collector being created, while the garbage collector is actively destroying an object.
Fixes #1121
> Fix !IsGarbageCollecting() assertion in ACesiumCreditSystem

- Config/FilterPlugin.ini
The Epic Marketplace team requested we do this in order to have Linux binaries correctly published in the Marketplace.
> Add Linux Binaries and Intermediate files to FilterPlugin.ini

- CHANGES.md
- CesiumForUnreal.uplugin
- package.json
I branched it off the v1.27.0 tag in order to keep it a small, bugfix only release.
> Merge the v1.27.1 release back into ue5-main

- CHANGES.md
- Source/CesiumRuntime/Private/GlobeAwareDefaultPawn.cpp
- Source/CesiumRuntime/Private/Tests/CesiumCameraManager.spec.cpp
- Source/CesiumRuntime/Private/Tests/CesiumTestHelpers.cpp
- Source/CesiumRuntime/Private/Tests/CesiumTestHelpers.h
- Source/CesiumRuntime/Private/Tests/GeoTransforms.spec.cpp
- Source/CesiumRuntime/Private/Tests/GlobeAwareDefaultPawn.spec.cpp
- Source/CesiumRuntime/Public/GlobeAwareDefaultPawn.h
In the Sublevels Sample, sometimes, upon arrival in Paris, the flight interpolation percentage would be exactly 1.0. Not just "displays as 1.0", but exactly equal to 1.0. And when that happened, the interpolation of the altitude flight curve would return 1.0, so the flight would put the altitude at its maximum rather than its destination height. This makes absolutely no sense, because the altitude interpolation key points are (0.0, 0.0), (0.5, 1.0), (1.0, 0.0). In other words, it should be 0.0 (minimum height) at the start and end, and 1.0 (maximum height) in the middle, just what you'd expect for altitude on a camera flight. Yet asking for the interpolated value at exactly 1.0 would return that value at 0.5 instead of the value at 1.0.
So stepping into UE's curve interpolation, I found …
> Fix rare-ish camera jump when arriving at a flight destination

- Source/CesiumRuntime/Private/CesiumGltfComponent.cpp
After #1126, generated flat normals are very wrong. This can be seen in Denver when set to ignore the unlit extension, for example.
> Fix incorrect flat normals.

- .github/workflows/build.yml
Our UE 5.1 build machine image previously used UE 5.1.0, and it has an apparent bug when doing Android builds. Some details here:
https://forums.unrealengine.com/t/5-1-missing-precompiled-manifest-error-when-building-code-plugin-for-android/691983
We had some hacky code in the build process to work around this. But after upgrading the build machine to use UE 5.1.1, the hack no longer works and should also no longer be necessary. So this PR removes it.
> Remove Android path hack after upgrade to UE 5.1.1.

- CHANGES.md
- Shaders/Private/CesiumPointAttenuationVertexFactory.ush
#1126 broke point cloud shading -- when attenuation is enabled, the point cloud disappears (though the outline is visible in the editor). The y-inversion matrix introduced in that change caused the quads to face the wrong way, so they wouldn't show up with back-face culling. You can confirm this by enabling "Two - Sided" on the Cesium base material; the point cloud does show up, although really dark because we're looking at the "back side" of all the quads.
This PR inverts the Y-offsets of the points in the shader, such that they will be corrected by the y-inversion matrix.
> Account for y-inversion when rendering attenuated points

- CHANGES.md
- Source/CesiumRuntime/Private/CesiumGltfComponent.cpp
Fixes #1180 
UnrealLightmass.exe is a separate process run via Swarm when building lighting. As reported in #1180, it (always? usually?) crashes when we attempt to build lighting (Build -> Build Lighting Only) for a level that has a Cesium3DTileset in it. Unfortunately it's build without any debug symbols, so I had to build it myself to debug it.
Having done that, I learned that the problem is that every `FStaticMeshLightingMesh` pointed to the same `FStaticMesh` instance, which really couldn't be right. And I learned that that was happening because, on import, all the static mesh references had the same GUID (all zeros!). Ok, so the problem seemed to be back in the Unreal Editor on the export side.
So, I traced through the code that exported the lightmass data, and yep, it was writing a …
> Don't crash when building lighting for a level with a Cesium3DTileset

- .github/workflows/build.yml
- CHANGES.md
- Shaders/Private/CesiumPointAttenuationVertexFactory.ush
Before this PR, the `v1.x` branch is the same as the `v1.28.0` tag. This PR merges in all the changes that are already in ue5-main that we intend to ship with v1.29.0. It's a mix of fast-forwards (for changes added before the first change that we _don't_ want to ship in this release landed in ue5-main) and cherry-picks (for changes added afterward).
> Merge changes for v1.29.0 from ue5-main into v1.x

- Source/CesiumRuntime/Public/CesiumCreditSystem.h
There is a widget subclass `CreditsWidgetClass` specified in CesiumCreditSystem.h that is currently set to be a subclass of a UUserWidget, so any user-created widget can be set in the editor for this variable. However, later code that uses this variable assumes that it is a subclass of UScreenCreditsWidget:
CesiumCreditSystem.cpp:254
```
CreditsWidget =
CreateWidget<UScreenCreditsWidget>(GetWorld(), CreditsWidgetClass);
```
At this point, if the user has inadvertently set an arbitrary widget for CreditsWidgetClass, then CreditsWidget will be invalid because CreditsWidgetClass is assumed to be a subclass of UScreenCreditsWidget.
This PR addresses that issue by making the TSubclassOf variable set to a UScreenCreditsWidget type in the first place, so that the user cannot specify an …
> Prevent crash when setting credit widget subclass

- Source/CesiumRuntime/Private/CesiumSubLevelSwitcherComponent.cpp
- Source/CesiumRuntime/Private/Tests/CesiumTestHelpers.h
These show up as compiler errors when building in non-unity mode.
> Add missing headers.

- .github/workflows/testWindows.yml
- Bump timeout for unit tests from 30 mins to 60 mins
- Fix "Run Cesium tests" step to show a red X when errors occur
- Show log and show report steps always try to show, even on error or cancelled build
- Rework "Evaluate tests results" to show pass / failed tests and show X if any failed
Improvements broken out from PR #1190 so they can be merged individually (and sooner)
> Improvements for unit test workflows on CI

- .github/workflows/build.yml
- Config/FilterPlugin.ini
The Unreal Marketplace build process for our plugin seems to a) delete our Linux intermediate files, and b) fail to produce new ones itself. As a workaround, the Marketplace team has told us to put our Linux intermediate files into a separate directory so that they can pass through Epic's build process unscathed. 🤷 So that's what this PR does. Users will also need to manually copy the files to the correct place, though, in order for Linux builds to work.
> Add workaround for Linux intermediates on the UE Marketplace.

- .github/workflows/buildWindows.yml
Because maybe the temp directory is the source of all the data we're writing to EBS?
> Put temp directory on the D drive

- .github/workflows/build.yml
We suspect that the macOS 13 image was recently updated and caused our ios52 builds to break. Revert to macOS 12, which seems to work fine.
Latest [broken builds](https://github.com/CesiumGS/cesium-unreal/actions/runs/6099938454/job/16553187907) show this
```
Operating System
macOS
13.5.1
22G90
```
Previous [good builds](https://github.com/CesiumGS/cesium-unreal/actions/runs/6069027505/job/16462820024) show
```
Operating System
macOS
13.5
22G74
```
> Fix ios52 CI build

- Source/CesiumRuntime/Private/Cesium3DTileset.cpp
- Source/CesiumRuntime/Private/CesiumGeoreference.cpp
- Source/CesiumRuntime/Private/CesiumGlobeAnchorComponent.cpp
- Source/CesiumRuntime/Private/CesiumSunSky.cpp
- Source/CesiumRuntime/Private/GlobeAwareDefaultPawn.cpp
- Source/CesiumRuntime/Public/CesiumGeoreference.h
This is PR into #1179 so merge that first.
It also depends on CesiumGS/cesium-native#696 so merge that first, too.
Between Unreal itself having double-precision vector and matrix types, and new capabilities in cesium-native (like `LocalHorizontalCoordinateSystem`), the `GeoTransforms` class is no longer needed.
This PR marks it deprecated and switches all of our uses of it to an alternative. I was really happy to see that this ends up deleting more code than it adds.
I didn't switch UCesiumGlobeAnchorComponent to use cesium-native's GlobeAnchor yet, so there's a little duplication because of that at the moment. That will be a separate PR.
> Deprecate GeoTransforms class

- Source/CesiumEditor/Private/CesiumEditorSubLevelMutex.cpp
- Source/CesiumRuntime/Public/CesiumSubLevelSwitcherComponent.h
Fixes the test that was disabled in #1218 because it failed in UE 5.3.
The problem is that in UE 5.3, when running headless, ActorComponents never have their TickComponent called. Why? Because there are no editor viewports, and so the engine only does a `ELevelTick::LEVELTICK_TimeOnly` type of tick, which explicitly does not tick actor or their components. Without the `UCesiumSubLevelSwitcherComponent` tick, there's nothing that disables other sub-levels when a new one is activated.
I don't know if this is a UE 5.3 bug. The closest thing I can find in the changelog is this:
> Disabled real-time viewports when the editor process is in the background and bThrottleCPUWhenNotForeground.
But in any case I've worked around it in this PR by making `CesiumEditorSubLevelMutex` now explicitly …
> Make sure editor sub-levels are hidden even when not ticking.

- CHANGES.md
- Source/CesiumRuntime/Private/Cesium3DTileset.cpp
- Source/CesiumRuntime/Private/CesiumActors.cpp
- Source/CesiumRuntime/Private/CesiumActors.h
- Source/CesiumRuntime/Private/CesiumCartographicPolygon.cpp
- Source/CesiumRuntime/Private/CesiumIonRasterOverlay.cpp
- Source/CesiumRuntime/Public/CesiumCartographicPolygon.h
- Source/CesiumRuntime/Public/CesiumIonRasterOverlay.h
Closes issue with same name, #1114 .
Based on the changes in #1111 , the only actors that could have previously had the `RF_Public` flag set would be `ACesium3DTileset`, `ACesiumCartographicPolygon`, and `UCesiumIonRasterOverlay` (actor component).
Hook into these classes' `PostLoad` and clear this flag if it set.
Tested using cesium-unreal-samples, 02_CesiumMelbourne and 08_CesiumClipping
> Clear RF_Public flag on our Actors in PostLoad

- .github/workflows/build.yml
- CesiumForUnreal.uplugin
We now require UE 5.1+. I haven't done all the potential code cleanup that we could do after removing 5.0; I've just removed it from CI.
> Remove Unreal Engine 5.0 support from CI.

- Source/CesiumRuntime/Private/CesiumPropertyTableProperty.cpp
- Source/CesiumRuntime/Private/Tests/CesiumPropertyTableProperty.spec.cpp
- Source/CesiumRuntime/Public/CesiumPropertyTableProperty.h
`PropertyTablePropertyViewType` was a `typedef` for a large `std::variant` defined in Cesium Native. It was so large that all of the normalized property versions had to be put in their own `std::variant`, and the two were then grouped under their own `std::variant` in Cesium for Unreal. While Visual Studio's compiler was able to handle this well, Clang would experience incredibly slow compilation times and often would not be able to complete CI.
This replaces the `std::variant` with a `std::any`. The original property type is stored in the `FCesiumMetadataValueType`, and the struct can be used to re-find the C++ type to `std::any_cast` to. This allows Clang + CI to finally compile successfully, and to _somewhat_ reduce the size of our object files.
> Don't use `std::variant` in `FCesiumPropertyTableProperty`

- .github/workflows/build.yml
- .github/workflows/buildWindows.yml
- Source/CesiumRuntime/Public/Cesium3DTileset.h
Fix bug where CI wouldn't show an error on the build step. 
This would not only lead to a false positive, but would also upload artifacts even when the build wasn't valid.
Applies to Windows builds only.
Closes #1235
> Improve build error handling on Continuous Integration (CI)

- Source/CesiumRuntime/Private/Cesium3DTilesetRoot.cpp
This pull request fixes a bug in the GLTF primitive component positioning. Previously, the GLTF primitive component were using absolute coordinates to set their location:
```
Gltf->SetUsingAbsoluteLocation(true);
```
but now its using relative. 
Because the GLTF primitive component is attached to the Cesium3DTilesetRoot component, the relative transform is already applied, and it was being applied twice.
> Fix GLTF primitive component positioning

- CHANGES.md
- Source/CesiumRuntime/Private/Cesium3DTileset.cpp
Fixes a crash where a level with a Level Sequence Actor has no Level Sequence Player.
> Check if Level Sequence Asset is empty

- CHANGES.md
- Source/CesiumRuntime/Private/CesiumGlobeAnchorComponent.cpp
I noticed that when opening the DynamicPawn in the Blueprint Editor, Cesium for Unreal spams endless messages to the log about the pawn's GlobeAnchor not being registered:
```
LogCesium: Error: Cannot get the rotation from CesiumGlobeAnchorComponent GlobeAnchor because the component is not yet registered or does not have a valid CesiumGeoreference.
LogCesium: Warning: CesiumGlobeAnchorComponent GlobeAnchor globe position is invalid because the component is not yet registered.
LogCesium: Warning: CesiumGlobeAnchorComponent GlobeAnchor globe position is invalid because the component is not yet registered.
```
This is normal and expected in this scenario, so I changed the code to avoid the spam.
It doesn't make sense to set the globe anchor position/orientation parameters in this scenario, …
> Don't spam the log when a globe anchor does not have a world.

- CHANGES.md
- Source/CesiumRuntime/CesiumRuntime.Build.cs
- Source/CesiumRuntime/Private/Tests/UnrealAssetAccessor.spec.cpp
- Source/CesiumRuntime/Private/UnrealAssetAccessor.cpp
- Source/CesiumRuntime/Public/UnrealAssetAccessor.h
Fixes #378 
I was updating the [Adding Datasets](https://cesium.com/learn/unreal/unreal-datasets/) tutorial for v2.0, and it seemed easier (or at least more rewarding) to fix file URLs rather than document all the caveats surrounding their use.
> Add support for file:/// URLs across platforms and UE versions

- .github/workflows/build.yml
This should greatly reduce the size of the .o files we ship on these platforms.
> Run objcopy --compress-debug-sections on Android and Linux binaries.

- CHANGES.md
- Source/CesiumRuntime/Public/CesiumFeaturesMetadataComponent.h
- Source/CesiumRuntime/Public/CesiumMetadataPropertyDetails.h
Fixes #1257 by setting default values for struct members that were missing them.
> Fix uninitialized struct members

- Source/CesiumRuntime/Private/Tests/CesiumLoadTestCore.cpp
- Source/CesiumRuntime/Private/Tests/CesiumLoadTestCore.h
- Source/CesiumRuntime/Private/Tests/CesiumLoadTestSamples.cpp
- Source/CesiumRuntime/Private/Tests/CesiumSceneGeneration.cpp
- Source/CesiumRuntime/Private/Tests/CesiumSceneGeneration.h
- Source/CesiumRuntime/Private/Tests/Google3dTilesLoadTest.cpp
New tests to show loading time changes when tweaking a tileset's `MaximumSimultaneousTileLoads` property.
Also, update tests to fetch Google 3D Tiles through Cesium Ion.
This defaults to 20, but may benefit from being tweaked based on your physical location and network connectivity.
* Added new `VaryMaxTileLoads` test to sample tests
* Added new `VaryMaxTileLoads` test to Google 3D Tiles tests
* Added new Melbourne locale to sample tests
* Add report step at end of tests to summarize all passes at a glance
(animation sped up for convenience)
> Add performance tests for investigating MaximumSimultaneousTileLoads

- CHANGES.md
- Source/CesiumEditor/Private/CesiumEditor.cpp
- Source/CesiumEditor/Private/CesiumGeoreferenceCustomization.cpp
- Source/CesiumRuntime/Private/CesiumGeoreference.cpp
- Source/CesiumRuntime/Private/CesiumSubLevelComponent.cpp
- Source/CesiumRuntime/Public/CesiumGeoreference.h
- Source/CesiumRuntime/Public/CesiumSubLevelComponent.h
Numerous sub-level workflow improvements:
* New Cesium Actors are now created with the same world transform as the CesiumGeoreference. This is particularly important when Actors are created in sub-levels, because the previous behavior (an identity world transform) would end up with them misaligned with other Cesium globe things. Outside sub-levels, it should behave the same as before, but it's hopefully a bit clearer. Previously we created the new Tileset (for example) with an identity FTransform, and then moved it under the CesiumGeoreference while preserving the (identity) _relative_ transform. That would cause it to adopt the same world transform as the CesiumGeoreference. Now we create it explicitly with the same world transform as the CesiumGeoreference, and preserve the world …
> Cesium sub-level improvements

- Source/CesiumRuntime/Private/CesiumFlyToComponent.cpp
Closes #1236 
Revert logic that calculates flight rotation axis and angle to use `glm::` functions, like we did a few versions ago. 
The Unreal counterparts have hidden epsilons that were returning (1,0,0) for the rotation axis when small flight distances were needed.
Easy to reproduce in cesium-unreal-samples. Open 04_CesiumSublevels. Enter Play. Move somewhere else on the roof top, then press '1'.
> Fix inaccurate and "snappy" flights when using FlyTo component

- Source/CesiumRuntime/Private/Tests/CesiumLoadTestCore.cpp
- Source/CesiumRuntime/Private/Tests/CesiumLoadTestCore.h
- Source/CesiumRuntime/Private/Tests/CesiumLoadTestSamples.cpp
- Source/CesiumRuntime/Private/Tests/Google3dTilesLoadTest.cpp
This fixes some errors caused by missing includes in a non-unity build. Also fixed a warning caused by the compiler being unable to see that a variable would actually be initialized.
> Add missing includes, fix a warning

- Source/CesiumRuntime/Private/Tests/CesiumPropertyTexture.spec.cpp
- Source/CesiumRuntime/Private/Tests/CesiumPropertyTextureProperty.spec.cpp
They were added previously, but not in this namespace.
CI executes the tests from this namespace. If your test isn't here, it won't run.
> Move new unit tests to Cesium.Unit.X namespace

- Source/CesiumEditor/Private/Cesium3DTilesetCustomization.cpp
- Source/CesiumEditor/Private/Cesium3DTilesetCustomization.h
- Source/CesiumEditor/Private/CesiumEditor.cpp
Closes #1260 .
Move Cesium category so it's right after Transform and before Rendering.
These changes allow us to do future customization as well.
> Cesium3DTileset custom category ordering

- Source/CesiumEditor/Private/CesiumIonSession.cpp
- Source/CesiumEditor/Private/IonLoginPanel.cpp
Fixes two bugs:
1. When resuming, the connection could still be connected even when the API url is incorrect and so the UI appears that the user is logged in. Now, the Login Panel shows instead.
2. When the API url is being fetched, the ConnectionStatus Widget would show the URL to be blank and the Cancel button wouldn't work. Now, the ConnectionStatus Widget will appear only after the Server has acquired the API url and tries to authorize.
> Multiple cesium ions review

- CHANGES.md
- Source/CesiumRuntime/Private/CesiumFlyToComponent.cpp
Fixes #1332
I wrote in the linked issue that I didn't think it was worth fixing the problem, versus porting the flight code from CesiumJS. But then I realized the fix is really easy: just scale the positions to the ellipsoid before computing the start and end directions. So here it is.
> Fix jump at end of flights.

- CHANGES.md
- Source/CesiumRuntime/Private/CesiumActors.cpp
Fixes #1289.
Despite `WITH_EDITOR` being defined, sometimes `GEditor` is nullptr when `CesiumActors::shouldValidateFlags` is called. This change adds a check to return false when that's the case instead of crashing.
> Fix crash due to GEditor being nullptr

- CHANGES.md
- Source/CesiumRuntime/Private/CesiumEncodedFeaturesMetadata.cpp
- Source/CesiumRuntime/Private/CesiumEncodedMetadataUtility.cpp
- Source/CesiumRuntime/Private/CesiumTextureUtility.cpp
This is a simple change that significantly reduces the amount of (CPU) memory used by textures on non-Windows systems.
We create textures in most situations and on most platforms by populating Unreal's `FBulkData` class with the raw pixel data from the glTF or raster overlay. Then, sometime later, Unreal's uploads it to the GPU. I noticed while spelunking through the Unreal source code while working on #1327 that `FBulkData` has a flag: `BULKDATA_SingleUse`. When this is set, Unreal directly grabs the buffer from the FBulkData as the source of the GPU upload, and frees it afterward. It's single use because we can't use that buffer ourselves after Unreal has grabbed it. When it's _not_ set (which is the default), Unreal copies the bulk data again, uses the copy as the source of the upload, …
> Reduce texture memory usage on non-Windows systems

- CHANGES.md
- Source/CesiumRuntime/Private/CesiumGltfComponent.cpp
Fixes #1268.
Enabling the setting to Ignore `KHR_materials_unlit` forces the glTF implementation to compute flat normals for the primitive, as per the glTF spec. However, we can't compute flat normals for points or line primitives, causing a crash if this setting was enabled on a point cloud. This change adds a check that ignores this setting if specified on a non-triangle primitive.
> Fix crash when enabling Ignore `KHR_materials_unlit` on point clouds

- CHANGES.md
- Source/CesiumRuntime/Private/CesiumTextureUtility.cpp
This PR makes the "Texture Memory Used" stat of the "Memory" group:
And the "TextureGroup" stats:
show the memory used by our textures even on D3D11 and D3D12. Previously, our custom texture creation path side-stepped Unreal's counter logic, so the memory used by our textures was conspiciously missing from these debug displays.
This was a pain because some things necessary to make it work are inexplicably private to the engine. Specifically `FTextureResource::TextureGroupStatFNames` is a public static field in a class declared in a public header file. But trying to use it results in linker errors on Windows because Epic didn't (forgot to?) mark it as DLL exported. So I had to duplicate the engine code that declares a stat group for each texture group.
> Track texture size stats in custom D3D texture loading path.

- Documentation/release-process.md
- Source/CesiumRuntime/Private/Tests/CesiumSceneGeneration.cpp
They can't run without a valid ion token. Looks like we missed updating it on the last release.
Also update the release documentation that mentions a separate google key. This is no longer needed.
https://github.com/CesiumGS/cesium-unreal/blob/Update-ion-token-for-performance-tests/Documentation/release-process.md#verify-the-code
> Update ion token for performance tests

- Documentation/release-process.md
While looking at #1352 I noticed that our release documentation was rather out-of-date, so I did a pass to clean it up and remove unnecessary steps (e.g. separate releases for UE4 and UE5).
> Update release documentation for UE5

- .github/workflows/buildWindows.yml
- Source/CesiumRuntime/Private/CesiumSunSky.cpp
There's been a few reports in our forums ([here](https://community.cesium.com/t/cesium-causes-access-violation-crash-in-unreal-5-3-2/28696) and [here](https://community.cesium.com/t/my-project-cannot-be-opened-hello-i-used-cesuim-to-make-the-project-for-a-month-suddenly-cannot-be-opened/29660)) that show some users are experiencing a crash on the line `FVector location = transform.TransformPosition(getViewLocation(this->GetWorld()));` in `CesiumSunSky.cpp`. While none of us are able to reproduce this bug, it seems likely that some sort of race condition is resulting in `this->GetWorld()` returning nullptr. Even if this isn't the source of these crashes, it's a good check to add anyways. I've also gone through `CesiumSunSky` to add checks to other locations where an unexpected nullptr …
> Add checks to CesiumSunSky to prevent possible crashes

- extern/CMakeLists.txt
This assert is triggering in debug, when it shouldn't.
It may look like the cause is the latest cesium-native changes, https://github.com/CesiumGS/cesium-native/pull/806 ... but really the problem is that the cesium-for-unreal build defines `NDEBUG`, even in debug builds (!!). 
For the previously mentioned PR, this resulted in a mismatch in the header of `ReferenceCounted`. The member declaration order was not the same in the cesium-native and cesium-for-unreal builds. A subtle bug.
Since there may be other subtle bugs we may not be aware of, change the build of cesium-native to always define NDEBUG, even in debug, to avoid these code mismatches.
> Fix IntrusivePointer threadID assert

- .github/workflows/buildLinux.yml
Otherwise an outdated package source seems to break the removal process and cause CI builds to fail. Which is infurating.
> `apt update` before `apt remove`

- CHANGES.md
- Source/CesiumEditor/Private/Cesium3DTilesetCustomization.cpp
- Source/CesiumEditor/Private/Cesium3DTilesetCustomization.h
- Source/CesiumEditor/Private/CesiumGeoreferenceCustomization.cpp
- Source/CesiumEditor/Private/CesiumGeoreferenceCustomization.h
- Source/CesiumEditor/Private/CesiumGlobeAnchorCustomization.cpp
- Source/CesiumEditor/Private/CesiumGlobeAnchorCustomization.h
Fixes #1363 .
For all of our classes deriving from `IDetailCustomization`, change the call to `::UnregisterCustomClassLayout` to use a saved version of the class name that we called `::RegisterCustomClassLayout` with.
We don't want to access that class with `::StaticClass()` during shutdown, it's already been sent to the garbage collector to be destroyed. Sometimes the GC wouldn't have gotten to it yet (and you don't crash). But other times the static class data is garbage and we'll get an access violation.
I could reproduce this 100% of the time in UE 5.4 in DebugGame, with the following UI layout...
> Fix intermittent shutdown crash (static class GC'd)

- Source/CesiumRuntime/CesiumRuntime.Build.cs
- Updates for KTX library changes: `ktx_read` -> `ktx`
- Adds new `CesiumQuantizedMeshTerrain` namespace
> Update `CesiumRuntime.Build.cs` for Cesium Native changes

- .github/workflows/buildAndroid.yml
- .github/workflows/buildLinux.yml
- .github/workflows/buildMac.yml
- .github/workflows/buildWindows.yml
- .github/workflows/buildiOS.yml
This avoids UE 5.4 considering our non-read-only source files to be part of the working set and leaving them out of the unity build.
Fixes #1410
> Force "None" source code provider on CI.

- Source/CesiumRuntime/Private/Tests/CesiumTextureUtility.spec.cpp
Closes #1434.
I repro'd this error by doing this:
1) Downloaded CesiumForUnreal-53-v2.5.0.zip from the releases page
2) Open Unreal 5.3, create a new Blueprints project
3) Unzip the plugin to this projects "Plugins" folder (I had to create this)
4) Open the test project, enable the Cesium For Unreal plugin
5) Close Unreal
6) Delete the contents of `<testProject>/Plugins/CesiumForUnreal/Binaries`
7) Open the test project again, it should ask you to rebuild
8) When it finishes, you'll see a popup dialog that says there were errors (you can see details in `<testProject>/Saved/Logs`
Using the build from this PR should fix this error.
> Add missing header for some builds

- CHANGES.md
- Source/CesiumRuntime/Private/Cesium3DTileset.cpp
- Source/CesiumRuntime/Private/CesiumGltfComponent.cpp
- Source/CesiumRuntime/Private/CesiumTextureUtility.cpp
- Source/CesiumRuntime/Private/CesiumTextureUtility.h
- Source/CesiumRuntime/Private/Tests/CesiumTextureUtility.spec.cpp
This builds on #1431 so merge that first.
This PR fixes a bug reported on the forum:
https://community.cesium.com/t/textures-appears-white-when-used-multiple-times-on-same-gltf/32278
The model and instructions there make it easy to reproduce.
In this model, two primitives both reference the same material, and that material has a `baseColorTexture`. So when preparing the glTF for use with Unreal, and processing both of the primitives, we indirectly end up processing the same texture twice.
The first time we process the texture, the associated image's `ImageCesium` has pixel data. So in a worker thread, we create a new `FCesiumTextureResourceBase` (RHI texture resource) from it, and then clear the pixel data. So far so good.
The next time we process the texture, we see that an …
> Fix missing textures caused by sharing a single texture between multiple primitives

- .github/workflows/build.yml
- Config/FilterPlugin.ini
Produces a new `SourceOnly` build artifact from the Combine steps, which excludes the `Binaries` and `Intermediates` directories. These are produced by Epic's Marketplace build process, and including them has apparently started to cause that process to fail (see #1433).
I've also eliminated the old `LinuxIntermediates` directory. If we're really lucky, the now-less-confused Epic build process will now produce Linux binaries the way it's supposed to. But if not, the LinuxIntermediates directory wasn't doing anyone much good anyway. People needed to know to copy it to Intermediates in order to build for Linux in order to use it, and at that point why not just use our releases on GitHub instead of Epic's?
> Create build without Binaries/Intermediates for the Marketplace.

- Source/CesiumRuntime/Private/CesiumCreditSystem.cpp
- Source/CesiumRuntime/Private/CesiumSubLevelSwitcherComponent.cpp
UE deprecated `ULevelStreaming::ECurrentState` in UE 5.2 and removed it in 5.3. We had some ifdef's to use the new type in 5.3+, but because we were still using the (now deprecated) type in 5.2, we were getting tons of warnings. So this PR just removes the ifdef and uses the new type in all UE versions.
> Fix warnings in UE 5.2.

- CHANGES.md
- Source/CesiumRuntime/Private/CesiumSunSky.cpp
Check `pViewport` validity before dereferencing it.
> Fix crash caused by CesiumSunSky when no viewport is activated in the Editor.

- .github/workflows/build.yml
Apparently we need `workflow_dispatch` in our CI to dispatch workflows manually? Anyways, this would be helpful for running CI for community PRs that don't trigger the `push` event.
> Let CI be dispatched manually

- .github/workflows/build.yml
- Documentation/Doxyfile
Bringing cesium-unreal in line with cesium-unity and cesium-native, this change adds a step to CI that builds the Doxygen documentation for us.
> Add Doxygen step to CI

- Source/CesiumEditor/Private/CesiumGlobeAnchorCustomization.cpp
Came up in the forum [here](https://community.cesium.com/t/cesium-for-unreal-v2-7-0-build-errors/33439/5)
```
[1/4] Compile [x64] CesiumGlobeAnchorCustomization.cpp
C:\path\to\project\Plugins\CesiumForUnreal\Source\CesiumEditor\Private\CesiumGlobeAnchorCustomization.cpp(239): error C2664: 'bool IsValid(const UObject *)': cannot convert argument 1 from 'ACesiumGeoreference *' to 'const UObject *'
C:\path\to\project\Plugins\CesiumForUnreal\Source\CesiumEditor\Private\CesiumGlobeAnchorCustomization.cpp(239): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or parenthesized function-style cast
C:\toolchains\unreal\ue-5.3.2-release\Engine\Source\Runtime\CoreUObject\Public\UObject\Object.h(1771): note: see declaration of 'IsValid' …
```
> Add missing include for specific UE 5.3 builds

- CHANGES.md
- Source/CesiumRuntime/Private/CesiumMetadataValue.cpp
- Source/CesiumRuntime/Private/CesiumPropertyArrayBlueprintLibrary.cpp
- Source/CesiumRuntime/Private/CesiumPropertyTableProperty.cpp
- extern/CMakeLists.txt
Fixes #1380 
We're seeing `bad_any_cast` exceptions when loading tilesets with metadata, in release builds, on every platform except Windows. The cause appears to be that cesium-native is compiled with runtime type information (RTTI) enabled, but Cesium for Unreal - as required by Unreal Engine itself - is compiled with RTTI disabled. Windows isn't fussed about this, but apparently it causes subtle problems on Linux/Android/Apple.
> Fix bad_any_cast errors by disabling RTTI when building cesium-native

- CHANGES.md
- Source/CesiumRuntime/Private/CesiumGltfComponent.cpp
- Source/CesiumRuntime/Private/CesiumMetadataPickingBlueprintLibrary.cpp
- Source/CesiumRuntime/Private/CesiumPrimitive.h
- Source/CesiumRuntime/Private/Tests/CesiumFeatureIdSet.spec.cpp
- Source/CesiumRuntime/Private/Tests/CesiumFeatureIdTexture.spec.cpp
- Source/CesiumRuntime/Private/Tests/CesiumMetadataPickingBlueprintLibrary.spec.cpp
- Source/CesiumRuntime/Private/Tests/CesiumPropertyTexture.spec.cpp
Fixes #1250
Lending further support to my theory that "anytime a software developer is typing the word 'epsilon', they're typing a bug"...
(See my previous rant about epsilons in CesiumGS/cesium-native#914)
We've had trouble with Chaos physics ever since Unreal Engine switched to it by default. The first problem was that Chaos would frequently crash in debug builds, or hang and spam the log in release builds, when doing collisions against many of our meshes (#1084). It was caused by checking for (and logging) "degenerate triangles". So, we decided to filter out degenerate triangles from our meshes using the same test that Chaos itself uses (#1106).
That worked well in that it stopped the crashing and freezing. But we still occasionally heard reports (#1250) of failed lined traces against …
> Fix Chaos physics epsilon silliness by scaling meshes up and then down.

- CHANGES.md
- Source/CesiumRuntime/Private/CesiumGltfComponent.cpp
Instanced translations were missing the `positionScaleFactor`, which made instances stack on top of each other incorrectly. Thanks @WxpGiser for the fix!
This fixes the translation errors in #1496, but there are still lingering issues, so I'll leave that open for now.
> Add missing scale factor to instanced translations

- CHANGES.md
- Source/CesiumRuntime/Private/CesiumRasterOverlay.cpp
- Source/CesiumRuntime/Public/CesiumRasterOverlay.h
This PR came out of this community forum post:
https://community.cesium.com/t/remove-clipping-cesiumpolygonrasteroverlay-added-during-runtime/32520/6
It makes it possible to call the `Destroy Component` Blueprint function on a raster overlay from outside the Cesium3DTileset Actor, and have it actually work.
It fixes a small bug where calling `Refresh` on an inactive `CesiumRasterOverlay` would cause that overlay to appear on the tileset. Until the next time the Tileset was refreshed, and then it would disappear.
It also adds some more detailed documentation for the `AddToTileset`, `RemoveFromTileset`, `Refresh`, `Activate`, and `Deactivate` methods on `CesiumRasterOverlay`.
> Raster overlay lifecycle and doc improvements

- .github/workflows/buildApple.yml
The [latest update](https://github.com/actions/runner-images/compare/macos-14-arm64/20240818.4...macos-14-arm64/20240827.4#diff-5c04a529d3c8adf7a5f23afe544071dad1853e281c9c7b44cd8d626b6c57444d) to the GitHub Actions macos-14 runner has drastically less disk than the previous image version, mostly because more stuff is installed. So this PR uninstalls some of that stuff so we have enough space for our builds again.
See here:
https://github.com/actions/runner-images/issues/10511
> Fix macOS build by freeing up disk space on the runner

- Source/CesiumRuntime/Private/UnrealAssetAccessor.cpp
- Added include for CesiumCommon which contains the definition of the engine version preprocessor
- Fixes #1519
> Fixed build for Unreal Engine 5.4

- CHANGES.md
- Source/CesiumRuntime/Private/CesiumEncodedFeaturesMetadata.cpp
- Source/CesiumRuntime/Private/CesiumEncodedFeaturesMetadata.h
- Source/CesiumRuntime/Private/CesiumFeaturesMetadataComponent.cpp
- Source/CesiumRuntime/Private/CesiumGltfComponent.cpp
In our metadata handling code, I found some unfortunate typos that happened as a result of overzealous copy-pasting. For some reason the `encodedProperty.offset` value was being passed for the `scale`, `noData`, and `default` value properties, which is obviously wrong. 🙃  Plus, I had typoed a `+` sign as an `=` sign, so one parameter was never being set.
This PR does two things:
1. Fixes the aforementioned bugs
2. Moves the `Set____ParameterValues` functions from `CesiumGltfComponent.cpp` to `CesiumEncodedFeaturesMetadata.h`. This was not strictly necessary, but I think this organization is helpful for decreasing the complexity of `CesiumGltfComponent`, and for putting the code closer to the rest of the `CesiumEncodedFeaturesMetadata` functionality.
If you'd like, you can verify that …
> Fix incorrect metadata property values being sent to material

- Source/CesiumRuntime/Private/Cesium3DTileset.cpp
- Source/CesiumRuntime/Private/Tests/SampleHeightMostDetailed.spec.cpp
This depends on CesiumGS/cesium-native#952 so merge that first.
> Handle SampleHeightMostDetailed on tilesets that completely fail to load, and add a test.

- CHANGES.md
- Source/CesiumRuntime/Private/CesiumGltfComponent.cpp
- Source/CesiumRuntime/Private/CesiumSunSky.cpp
- Source/CesiumRuntime/Public/CesiumSunSky.h
I originally set out to fix the clearly-incorrect normals for tilesets with `KHR_materials_unlit` (#1528). The immediate cause of the bug was that it wasn't taking into account the scaled positions introduced in #1465. But the code was also set up to compute one normal for the entire tile, based on the ellipsoid surface normal at the bounding volume origin. This was sure to create lighting discontinuities at the edges of tiles. So I decided to change that. Meshes with `KHR_materials_unlit` are now given a per-vertex normal which is the ellipsoid surface normal at that position, which looks a lot better. (note: the meshes already had per-vertex normals, the change is only to how they're computed)
I also noticed that we were unnecessarily duplicating vertices for unlit meshes. glTF requires …
> Fix `KHR_materials_unlit` normals, improve atmosphere appearance with Google Photorealistic 3D Tiles

- CHANGES.md
- Source/CesiumRuntime/Public/CesiumSampleHeightResult.h
Unreal is reporting that the two fields in this class are not initialized. This is probably harmless, but good (and easy) to fix.
As reported here:
https://community.cesium.com/t/fcesiumsampleheightresult-errors/35906
> Initialize fields in FCesiumSampleHeightResult.

- CHANGES.md
- Source/CesiumRuntime/Private/Cesium3DTileset.cpp
Fixes #1549. The cesium-native side isn't included yet since I didn't want to complicate things between PRs like #1552 and #1539.
> Fix `SampleHeightMostDetailed` crash on `Cesium3DTileset` with raster overlay

- CHANGES.md
- Source/CesiumRuntime/Private/CesiumPolygonRasterOverlay.cpp
- Source/CesiumRuntime/Public/CesiumPolygonRasterOverlay.h
Use a soft object pointer to store references to cartographic polygons in other level instances (#1544 ).
> Use a soft object reference for cartographic polygons

- Source/CesiumRuntime/Private/CesiumGltfTextures.cpp
- Source/CesiumRuntime/Private/CesiumTextureUtility.cpp
Usually this happens because the `ImageAsset` failed to load, perhaps because the URL is invalid.
Also updates cesium-native to include CesiumGS/cesium-native#1016, so merge that first.
> Don't crash if an Image is missing its ImageAsset

- CHANGES.md
- Source/CesiumRuntime/Private/CesiumSubLevelSwitcherComponent.cpp
Fixes #1575 
If a sublevel fails to load, we should not block other sublevels from loading. We can treat it as being unloaded.
> Treat failed to load as unloaded sublevels

- Source/CesiumRuntime/Private/Tests/CesiumSceneGeneration.cpp
Updating `SceneGenerationContext::testIonToken` to the Cesium for Unreal Samples v2.12.0 token to fix broken tests.
> Update `testIonToken` to latest Unreal Samples token

- Source/CesiumRuntime/CesiumRuntime.Build.cs
- Source/CesiumRuntime/Private/GeoTransforms.cpp
At the moment, `GLM_FORCE_SIZE_T_LENGTH` is still defined in the Unreal Build.cs, which - after we removed this define from Cesium Native - means linker errors result when trying to build Cesium for Unreal with the latest changes from Cesium Native. We can fix this by simply removing the define.
Also, I've been receiving errors related to using an experimental header without defining `GLM_ENABLE_EXPERIMENTAL`, despite the only place an experimental header is used in this codebase coming after a `#define GLM_ENABLE_EXPERIMENTAL` declaration. I don't know what's causing this - something to do with Unreal's unity build? - but it can be fixed by defining `GLM_ENABLE_EXPERIMENTAL` in the Build.cs.
> Fix build with GLM changes in Cesium Native

- .github/ISSUE_TEMPLATE/bug_report.yaml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.yaml
This follows CesiumJS's lead by adding issue templates to the repo. Hopefully the bug report form, in particular, streamlines the process for creating such reports :smile:
> Add issue templates

- CHANGES.md
- Source/CesiumRuntime/Private/CesiumSampleHeightMostDetailedAsyncAction.cpp
- Source/CesiumRuntime/Private/Tests/SampleHeightMostDetailed.spec.cpp
Fixes #1562. The `SampleHeightMostDetailed` blueprint function will currently crash if called without a valid `ACesium3DTileset` parameter. This PR adds a null check that returns an empty set of results and a warning if called with an invalid tileset.
> Check for null tileset in SampleHeightMostDetailed

- CHANGES.md
- Source/CesiumRuntime/Private/CesiumTileMapServiceRasterOverlay.cpp
- Source/CesiumRuntime/Private/CesiumUrlTemplateRasterOverlay.cpp
- Source/CesiumRuntime/Private/CesiumWebMapServiceRasterOverlay.cpp
- Source/CesiumRuntime/Private/CesiumWebMapTileServiceRasterOverlay.cpp
- Source/CesiumRuntime/Public/CesiumTileMapServiceRasterOverlay.h
- Source/CesiumRuntime/Public/CesiumUrlTemplateRasterOverlay.h
- Source/CesiumRuntime/Public/CesiumWebMapServiceRasterOverlay.h
- Source/CesiumRuntime/Public/CesiumWebMapTileServiceRasterOverlay.h
Fixes CesiumGS/cesium-native#1067, at least for Unreal. This change adds `RequestHeaders` properties to `CesiumTileMapServiceRasterOverlay`, `CesiumUrlTemplateRasterOverlay`, `CesiumWebMapServiceRasterOverlay`, and `CesiumWebMapTileServiceRasterOverlay`, allowing custom HTTP request headers to be specified on each.
> Add `RequestHeaders` properly to relevant raster overlays

- CHANGES.md
- Source/CesiumRuntime/Private/CesiumBoundingVolumeComponent.cpp
- Source/CesiumRuntime/Private/CesiumGlobeAnchorComponent.cpp
- Source/CesiumRuntime/Private/CesiumGltfComponent.cpp
- Source/CesiumRuntime/Private/CesiumGltfPrimitiveComponent.cpp
- Source/CesiumRuntime/Private/CesiumSubLevelComponent.cpp
- Source/CesiumRuntime/Private/Tests/VecMath.spec.cpp
- Source/CesiumRuntime/Private/VecMath.cpp
- Source/CesiumRuntime/Private/VecMath.h
> Fix matrix -> FTransform conversion for matrices with small scales

- Source/CesiumRuntime/Private/CalcBounds.cpp
- Source/CesiumRuntime/Private/CalcBounds.h
- Source/CesiumRuntime/Private/Cesium3DTileset.cpp
With the addition of a new `BoundingCylinderRegion` type to the `BoundingVolume` variant, we need to handle it in a couple of places in Cesium for Unreal or it causes a compiler errors.
> Update cesium-native, fix breakage caused by new bounding volume.

- Source/CesiumRuntime/Private/CesiumMetadataValue.cpp
- Source/CesiumRuntime/Private/Tests/CesiumMetadataValue.spec.cpp
- Source/CesiumRuntime/Public/CesiumMetadataValue.h
- Added an access to meta-data values as unsigned 64-bit integer
- Kept outside of UCesiumMetadataValueBlueprintLibrary because uint64 is not supported in blueprints (but this access can be useful in C++ code)
> Metadata: GetUnsignedInteger64

- Documentation/developer-setup-osx.md
Getting a useful stack trace from an Unreal app on an iOS device is surprisingly hard, but I worked out a way to do it while working on #1609 and wrote down some instructions.
> Add instructions for symbolicating iOS stack traces.

- CHANGES.md
- Source/CesiumRuntime/Private/CesiumRuntime.cpp
To quote @AlbanBERGERET-Epic in his message to us:
> One of our support team members just reported to me that one of our licensees was following your recommendation from [this post](https://community.cesium.com/t/ue-game-encounters-fatal-crash-when-game-directory-is-not-writable/22375/3), which is actually not accurate.
> 
> The best practice is to use `FPaths::ProjectUserDir` instead of `FPaths::EngineUserDir()`
> 
> - For a shipping build, both of these paths will redirect to C:\users\username\appdata, which is what we want.
> - For a development build, EngineUserDir will redirect to C:\Program Files, which is a problem if write-protected. But ProjectUserDir will use the local project folder, which should be good.
> 
> IDK if you're still using it in your latest plugin version (I did …
> Use `ProjectUserDir` instead of `EngineUserDir` for request cache path

- CHANGES.md
- Source/CesiumRuntime/Private/CesiumGltfComponent.cpp
Issue related to **UCesiumFeaturesMetadataComponent**.
If a given per-primitive feature attribute (let's say _FEATURE_ID_0) is referenced by distinct metadata tables in the model, and we instantiate a _UCesiumFeaturesMetadataComponent_ component to bake the latter in UVs, the UV texture coordinate index stored in the dedicated map (gltfToUnrealTexCoordMap) is wrong, because only the 1st layer of UVs will be transferred at the end, and not the latest one.
Indeed, at the end, when we transfer the UVs to the Unreal buffers, we use the size of the map as number of UV layers (and the map does not grow if we try to insert a duplicated key ('accessor' here)).
This case does happen with the tilesets generated by iTwin Mesh Export Service, where the same primitive features _FEATURE_ID_0 are …
> MetaData: Fixed wrong UV layer stored in map, when a same attribute is referenced multiple times

- CHANGES.md
- Source/CesiumRuntime/Private/CesiumGltfComponent.cpp
Depends on #1673 so merge that first.
This PR adds support for `TRIANGLE_FAN` primitives.
This was actually an accident... I was trying to do some cleanup in `loadPrimitive` and saw that the `CopyIndices` scope didn't have a branch for `TRIANGLE_FAN`. I thought that was a bug, so I added the code in, but then I realized that we didn't support it in the first place. It was trivial enough to add, so why not :shrug: 
- ~[ ] I have added or updated unit tests to ensure consistent code coverage as necessary.~
- ~[ ] I have updated the documentation as necessary.~
Test that this tileset loads (best viewed under a "True Origin" georeference): [MeshPrimitiveModes.zip](https://github.com/user-attachments/files/20353260/MeshPrimitiveModes.zip).
There should be a row of three hexagons.
> Add support for `TRIANGLE_FAN` primitives

- CHANGES.md
- Source/CesiumRuntime/Private/Cesium3DTileset.cpp
- Source/CesiumRuntime/Private/Cesium3DTilesetRoot.cpp
This PR resolves a crash that happened while duplicating a CesiumGeoreference in the Unreal Editor.
Fixes #1354.
~- [ ] I have added or updated unit tests to ensure consistent code coverage as necessary.~
~- [ ] I have updated the documentation as necessary.~
Simple to test, just duplicate or copy + paste a CesiumGeoreference and verify it won't crash. Also sanity check other operations like undo / redo, deleting, etc.
> Fix crash that results from duplicating a georeference

- Source/CesiumRuntime/Private/CesiumGltfComponent.cpp
Fixes #1686 
Fixes #1688
The modifications to support dynamic material instances also inadvertently broke the case where the user-provided material is not a material instance at all.
Also, the restructuring of the mesh creation introduced a bug where the Y component of the normals was inadvertently flipped when computing tangents.
No changelog entry because this is a regression since the last release.
I'll be merging this myself because we need to fix these two regressions for today's release.
> Support Materials, not just MaterialInstances, and fix normal flip when computing tangents

- Documentation/developer-setup-windows-gotchas.md
- Documentation/developer-setup-windows.md
Setting up a new Windows system to build Cesium for Unreal is shockingly difficult, due to compiler incompatibilities and the three build systems involved (vcpkg, CMake, and Unreal Build Tool). This PR adds a new doc page with all the details.
> Add Windows setup gotchas doc

- extern/CMakeLists.txt
Updated CMakeLists.txt to include default UNREAL_ENGINE_ROOT for MacOS. 
https://github.com/CesiumGS/cesium-unreal/issues/1715
Tested building on Mac.
> Added default UNREAL_ENGINE_ROOT value for MacOS

- CHANGES.md
- Source/CesiumRuntime/Private/CesiumPropertyAttribute.cpp
Missing declaration of `LogCesium` in _CesiumPropertyAttribute.cpp_
Tell me if you want an issue linked, I'll open one.
Setup a compilation CI in the sample project for example would avoid that kind of oversights.
> Add missing CesiumRuntime.h include for v2.18.0

- .github/workflows/build.yml
Windows SDK version `10.0.18362` is no longer supported as of version `20250811.1.0` on the Github Windows runner, which is the version that the Unreal 5.4 builds use. See https://github.com/actions/runner-images/issues/12776.
Although that version is the one officially used by Epic's build farm, the [release notes](https://dev.epicgames.com/documentation/en-us/unreal-engine/unreal-engine-5.4-release-notes?application_version=5.4) suggest it can still build with newer versions. So this bumps the version to the minimum version supported by the new runner image. The Windows UE 5.4 build passes and produces an artifact, and I haven't seen any unexpected behavior while going through the Cesium for Unreal Samples. So... maybe it's fine? 😁
> Bump Windows SDK Version on UE 5.4 CI

- CHANGES.md
- Source/CesiumRuntime/Private/CesiumRasterOverlay.cpp
- Source/CesiumRuntime/Public/CesiumRasterOverlay.h
1. Add a polygon raster overlay to Google Photorealistic 3D Tiles (probably any tileset will work) and point it to an actual Cartographic Polygon so that a rectangle is clipped out.
2. Delete the `CesiumPolygonRasterOverlay` from the tileset. The polygon cutout should disappear.
3. Press Ctrl-Z to undo the deletion. The polygon cutout should reappear.
4. Press Ctrl-Y to redo the deletion. CRASH!
The problem is that `UCesiumRasterOverlay` just holds a raw pointer to the underlying cesium-native `RasterOverlay`. In the specific scenario described above, the `Tileset` gets destroyed, which destroys the raster overlays, without the `UCesiumRasterOverlay` knowing about it. That leaves the `UCesiumRasterOverlay` holding a pointer to a deleted object.
I looked into fixing this, but it's not …
> Don't crash when undoing/redoing raster overlay deletion

- CHANGES.md
- Source/CesiumRuntime/Private/CesiumGltfComponent.cpp
- Source/CesiumRuntime/Private/CesiumGltfLinesComponent.cpp
- Source/CesiumRuntime/Private/CesiumGltfLinesComponent.h
- Source/CesiumRuntime/Private/CesiumGltfLinesSceneProxy.cpp
- Source/CesiumRuntime/Private/CesiumGltfLinesSceneProxy.h
This PR adds support for the `LINES`, `LINE_LOOP`, and `LINE_STRIP` primitive modes in glTF.
Apparently the only line mode supported in Unreal is `PT_LineList`, so the other two have to be converted into line lists with duplicate indices.
- ~[ ] I have added or updated unit tests to ensure consistent code coverage as necessary.~
- ~[ ] I have updated the documentation as necessary.~
The normals are off somehow for this model and I haven't figured out why? I added a clause to disable flat normal generation for non-triangle models (since that doesn't make much sense), but there's still some lighting variation among the lines themselves. You can see it when the sun angle is really extreme. 🤔 
Load this tileset under a georeference with **True Origin**: …
> Add support for glTF line primitives
